#ifndef __GN_GFX_XENONFORMAT_H__
#define __GN_GFX_XENONFORMAT_H__
// *****************************************************************************
/// \file
/// \brief   Xenon texture format definition
/// \author  chenli@@FAREAST (2007.8.22)
// *****************************************************************************

#ifndef MAKEFOURCC
#define MAKEFOURCC GN_MAKE_FOURCC
#endif

typedef enum
{
    GPUTEXTUREFORMAT_1_REVERSE                      = 0,
    GPUTEXTUREFORMAT_1                              = 1,
    GPUTEXTUREFORMAT_8                              = 2,
    GPUTEXTUREFORMAT_1_5_5_5                        = 3,
    GPUTEXTUREFORMAT_5_6_5                          = 4,
    GPUTEXTUREFORMAT_6_5_5                          = 5,
    GPUTEXTUREFORMAT_8_8_8_8                        = 6,
    GPUTEXTUREFORMAT_2_10_10_10                     = 7,
    GPUTEXTUREFORMAT_8_A                            = 8,
    GPUTEXTUREFORMAT_8_B                            = 9,
    GPUTEXTUREFORMAT_8_8                            = 10,
    GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP                = 11,
    GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP                = 12,
    GPUTEXTUREFORMAT_16_16_EDRAM                    = 13, // EDRAM render target only
    GPUTEXTUREFORMAT_8_8_8_8_A                      = 14,
    GPUTEXTUREFORMAT_4_4_4_4                        = 15,
    GPUTEXTUREFORMAT_10_11_11                       = 16,
    GPUTEXTUREFORMAT_11_11_10                       = 17,
    GPUTEXTUREFORMAT_DXT1                           = 18,
    GPUTEXTUREFORMAT_DXT2_3                         = 19,
    GPUTEXTUREFORMAT_DXT4_5                         = 20,
    GPUTEXTUREFORMAT_16_16_16_16_EDRAM              = 21, // EDRAM render target only
    GPUTEXTUREFORMAT_24_8                           = 22,
    GPUTEXTUREFORMAT_24_8_FLOAT                     = 23,
    GPUTEXTUREFORMAT_16                             = 24,
    GPUTEXTUREFORMAT_16_16                          = 25,
    GPUTEXTUREFORMAT_16_16_16_16                    = 26,
    GPUTEXTUREFORMAT_16_EXPAND                      = 27,
    GPUTEXTUREFORMAT_16_16_EXPAND                   = 28,
    GPUTEXTUREFORMAT_16_16_16_16_EXPAND             = 29,
    GPUTEXTUREFORMAT_16_FLOAT                       = 30,
    GPUTEXTUREFORMAT_16_16_FLOAT                    = 31,
    GPUTEXTUREFORMAT_16_16_16_16_FLOAT              = 32,
    GPUTEXTUREFORMAT_32                             = 33,
    GPUTEXTUREFORMAT_32_32                          = 34,
    GPUTEXTUREFORMAT_32_32_32_32                    = 35,
    GPUTEXTUREFORMAT_32_FLOAT                       = 36,
    GPUTEXTUREFORMAT_32_32_FLOAT                    = 37,
    GPUTEXTUREFORMAT_32_32_32_32_FLOAT              = 38,
    GPUTEXTUREFORMAT_32_AS_8                        = 39,
    GPUTEXTUREFORMAT_32_AS_8_8                      = 40,
    GPUTEXTUREFORMAT_16_MPEG                        = 41,
    GPUTEXTUREFORMAT_16_16_MPEG                     = 42,
    GPUTEXTUREFORMAT_8_INTERLACED                   = 43,
    GPUTEXTUREFORMAT_32_AS_8_INTERLACED             = 44,
    GPUTEXTUREFORMAT_32_AS_8_8_INTERLACED           = 45,
    GPUTEXTUREFORMAT_16_INTERLACED                  = 46,
    GPUTEXTUREFORMAT_16_MPEG_INTERLACED             = 47,
    GPUTEXTUREFORMAT_16_16_MPEG_INTERLACED          = 48,
    GPUTEXTUREFORMAT_DXN                            = 49,
    GPUTEXTUREFORMAT_8_8_8_8_AS_16_16_16_16         = 50,
    GPUTEXTUREFORMAT_DXT1_AS_16_16_16_16            = 51,
    GPUTEXTUREFORMAT_DXT2_3_AS_16_16_16_16          = 52,
    GPUTEXTUREFORMAT_DXT4_5_AS_16_16_16_16          = 53,
    GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16      = 54,
    GPUTEXTUREFORMAT_10_11_11_AS_16_16_16_16        = 55,
    GPUTEXTUREFORMAT_11_11_10_AS_16_16_16_16        = 56,
    GPUTEXTUREFORMAT_32_32_32_FLOAT                 = 57,
    GPUTEXTUREFORMAT_DXT3A                          = 58,
    GPUTEXTUREFORMAT_DXT5A                          = 59,
    GPUTEXTUREFORMAT_CTX1                           = 60,
    GPUTEXTUREFORMAT_DXT3A_AS_1_1_1_1               = 61,
    GPUTEXTUREFORMAT_8_8_8_8_GAMMA_EDRAM            = 62, // EDRAM render target only
    GPUTEXTUREFORMAT_2_10_10_10_FLOAT_EDRAM         = 63, // EDRAM render target only
} GPUTEXTUREFORMAT;
typedef enum
{
    GPUSIGN_UNSIGNED                                = 0,
    GPUSIGN_SIGNED                                  = 1,
    GPUSIGN_BIAS                                    = 2,
    GPUSIGN_GAMMA                                   = 3,
} GPUSIGN;

#define GPUSIGN_ALL_UNSIGNED (GPUSIGN_UNSIGNED | GPUSIGN_UNSIGNED<<2 | GPUSIGN_UNSIGNED<<4 | GPUSIGN_UNSIGNED<<6)
#define GPUSIGN_ALL_SIGNED (GPUSIGN_SIGNED | GPUSIGN_SIGNED<<2 | GPUSIGN_SIGNED<<4 | GPUSIGN_SIGNED<<6)

typedef enum
{
    GPUSWIZZLE_X                                    = 0,
    GPUSWIZZLE_Y                                    = 1,
    GPUSWIZZLE_Z                                    = 2,
    GPUSWIZZLE_W                                    = 3,
    GPUSWIZZLE_0                                    = 4,
    GPUSWIZZLE_1                                    = 5,
    GPUSWIZZLE_KEEP                                 = 7, // Fetch instructions only
} GPUSWIZZLE;

typedef enum
{
    GPUENDIAN_NONE                                  = 0,
    GPUENDIAN_8IN16                                 = 1,
    GPUENDIAN_8IN32                                 = 2,
    GPUENDIAN_16IN32                                = 3,
} GPUENDIAN;

#define GPUSWIZZLE_ARGB (GPUSWIZZLE_Z | GPUSWIZZLE_Y<<3 | GPUSWIZZLE_X<<6 | GPUSWIZZLE_W<<9)
#define GPUSWIZZLE_ORGB (GPUSWIZZLE_Z | GPUSWIZZLE_Y<<3 | GPUSWIZZLE_X<<6 | GPUSWIZZLE_1<<9)
#define GPUSWIZZLE_ABGR (GPUSWIZZLE_X | GPUSWIZZLE_Y<<3 | GPUSWIZZLE_Z<<6 | GPUSWIZZLE_W<<9)
#define GPUSWIZZLE_OBGR (GPUSWIZZLE_X | GPUSWIZZLE_Y<<3 | GPUSWIZZLE_Z<<6 | GPUSWIZZLE_1<<9)
#define GPUSWIZZLE_OOGR (GPUSWIZZLE_X | GPUSWIZZLE_Y<<3 | GPUSWIZZLE_1<<6 | GPUSWIZZLE_1<<9)
#define GPUSWIZZLE_OZGR (GPUSWIZZLE_X | GPUSWIZZLE_Y<<3 | GPUSWIZZLE_0<<6 | GPUSWIZZLE_1<<9)
#define GPUSWIZZLE_RZZZ (GPUSWIZZLE_0 | GPUSWIZZLE_0<<3 | GPUSWIZZLE_0<<6 | GPUSWIZZLE_X<<9)
#define GPUSWIZZLE_OOOR (GPUSWIZZLE_X | GPUSWIZZLE_1<<3 | GPUSWIZZLE_1<<6 | GPUSWIZZLE_1<<9)
#define GPUSWIZZLE_ORRR (GPUSWIZZLE_X | GPUSWIZZLE_X<<3 | GPUSWIZZLE_X<<6 | GPUSWIZZLE_1<<9)
#define GPUSWIZZLE_GRRR (GPUSWIZZLE_X | GPUSWIZZLE_X<<3 | GPUSWIZZLE_X<<6 | GPUSWIZZLE_Y<<9)
#define GPUSWIZZLE_RGBA (GPUSWIZZLE_W | GPUSWIZZLE_Z<<3 | GPUSWIZZLE_Y<<6 | GPUSWIZZLE_X<<9)

typedef enum
{
    GPUNUMFORMAT_FRACTION                           = 0,
    GPUNUMFORMAT_INTEGER                            = 1,
} GPUNUMFORMAT;

// A XENON_FORMAT constant is an identifier that uniquely identifies
// a texture or surface format.  It contains the following fields:

#define XENON_FORMAT_TEXTUREFORMAT_SHIFT   0       // GPUTEXTUREFORMAT
#define XENON_FORMAT_ENDIAN_SHIFT          6       // GPUENDIAN
#define XENON_FORMAT_TILED_SHIFT           8       // BOOL
#define XENON_FORMAT_SIGNX_SHIFT           9       // GPUSIGN
#define XENON_FORMAT_SIGNY_SHIFT           11      // GPUSIGN
#define XENON_FORMAT_SIGNZ_SHIFT           13      // GPUSIGN
#define XENON_FORMAT_SIGNW_SHIFT           15      // GPUSIGN
#define XENON_FORMAT_NUMFORMAT_SHIFT       17      // GPUNUMFORMAT
#define XENON_FORMAT_SWIZZLEX_SHIFT        18      // GPUSWIZZLE
#define XENON_FORMAT_SWIZZLEY_SHIFT        21      // GPUSWIZZLE
#define XENON_FORMAT_SWIZZLEZ_SHIFT        24      // GPUSWIZZLE
#define XENON_FORMAT_SWIZZLEW_SHIFT        27      // GPUSWIZZLE
#define XENON_FORMAT_SWIZZLE_SHIFT         XENON_FORMAT_SWIZZLEX_SHIFT

#define XENON_FORMAT_TEXTUREFORMAT_MASK    0x0000003f
#define XENON_FORMAT_ENDIAN_MASK           0x000000c0
#define XENON_FORMAT_TILED_MASK            0x00000100
#define XENON_FORMAT_SIGNX_MASK            0x00000600
#define XENON_FORMAT_SIGNY_MASK            0x00001800
#define XENON_FORMAT_SIGNZ_MASK            0x00006000
#define XENON_FORMAT_SIGNW_MASK            0x00018000
#define XENON_FORMAT_NUMFORMAT_MASK        0x00020000
#define XENON_FORMAT_SWIZZLEX_MASK         0x001c0000
#define XENON_FORMAT_SWIZZLEY_MASK         0x00e00000
#define XENON_FORMAT_SWIZZLEZ_MASK         0x07000000
#define XENON_FORMAT_SWIZZLEW_MASK         0x38000000
#define XENON_FORMAT_SWIZZLE_MASK          (XENON_FORMAT_SWIZZLEX_MASK | XENON_FORMAT_SWIZZLEY_MASK | XENON_FORMAT_SWIZZLEZ_MASK | XENON_FORMAT_SWIZZLEW_MASK)

#define MAKEXENON_FORMAT(TextureFormat, Endian, Tiled, TextureSign, NumFormat, Swizzle) \
            ((TextureFormat) << XENON_FORMAT_TEXTUREFORMAT_SHIFT | \
             (Endian) << XENON_FORMAT_ENDIAN_SHIFT | \
             (Tiled) << XENON_FORMAT_TILED_SHIFT | \
             (TextureSign) << XENON_FORMAT_SIGNX_SHIFT | \
             (NumFormat) << XENON_FORMAT_NUMFORMAT_SHIFT | \
             (Swizzle) << XENON_FORMAT_SWIZZLEX_SHIFT)

#define MAKEXENON_FORMAT2(TextureFormat, Endian, Tiled, TextureSignX, TextureSignY, TextureSignZ, TextureSignW, NumFormat, SwizzleX, SwizzleY, SwizzleZ, SwizzleW) \
            ((TextureFormat) << XENON_FORMAT_TEXTUREFORMAT_SHIFT | \
             (Endian) << XENON_FORMAT_ENDIAN_SHIFT | \
             (Tiled) << XENON_FORMAT_TILED_SHIFT | \
             (TextureSignX) << XENON_FORMAT_SIGNX_SHIFT | \
             (TextureSignY) << XENON_FORMAT_SIGNY_SHIFT | \
             (TextureSignZ) << XENON_FORMAT_SIGNZ_SHIFT | \
             (TextureSignW) << XENON_FORMAT_SIGNW_SHIFT | \
             (NumFormat) << XENON_FORMAT_NUMFORMAT_SHIFT | \
             (SwizzleX) << XENON_FORMAT_SWIZZLEX_SHIFT | \
             (SwizzleY) << XENON_FORMAT_SWIZZLEY_SHIFT | \
             (SwizzleZ) << XENON_FORMAT_SWIZZLEZ_SHIFT | \
             (SwizzleW) << XENON_FORMAT_SWIZZLEW_SHIFT)

#define MAKELINFMT(D3dFmt) ((D3dFmt) & ~XENON_FORMAT_TILED_MASK)

#define MAKESRGBFMT(D3dFmt) (((D3dFmt) & ~(XENON_FORMAT_SIGNX_MASK | XENON_FORMAT_SIGNY_MASK | XENON_FORMAT_SIGNZ_MASK)) | \
             ((GPUSIGN_GAMMA << XENON_FORMAT_SIGNX_SHIFT) | \
              (GPUSIGN_GAMMA << XENON_FORMAT_SIGNY_SHIFT) | \
              (GPUSIGN_GAMMA << XENON_FORMAT_SIGNZ_SHIFT)))

#define MAKELEFMT(D3dFmt) (((D3dFmt) & ~XENON_FORMAT_ENDIAN_MASK) | (GPUENDIAN_NONE << XENON_FORMAT_ENDIAN_SHIFT))

// An index XENON_FORMAT encodes the index size and endianness:

#define D3DINDEXFORMAT_ENDIAN_SHIFT     0       // GPUENDIAN
#define D3DINDEXFORMAT_32BITS_SHIFT     2       // BOOL

#define D3DINDEXFORMAT_ENDIAN_MASK      0x00000003
#define D3DINDEXFORMAT_32BITS_MASK      0x00000004

#define MAKEINDEXFMT(Is32Bits, Endian) \
            ((Is32Bits) << D3DINDEXFORMAT_32BITS_SHIFT | \
             (Endian) << D3DINDEXFORMAT_ENDIAN_SHIFT)

typedef enum _XENON_FORMAT
{
    // DXT:

    XENON_FORMAT_DXT1                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_DXT1, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT1             = MAKELINFMT(XENON_FORMAT_DXT1),

    XENON_FORMAT_DXT2                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_DXT2_3, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT2             = MAKELINFMT(XENON_FORMAT_DXT2),

    XENON_FORMAT_DXT3                 = XENON_FORMAT_DXT2,
    XENON_FORMAT_LIN_DXT3             = MAKELINFMT(XENON_FORMAT_DXT3),

    XENON_FORMAT_DXT3A                = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_DXT3A, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT3A            = MAKELINFMT(XENON_FORMAT_DXT3A),

    XENON_FORMAT_DXT3A_1111           = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_DXT3A_AS_1_1_1_1, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT3A_1111       = MAKELINFMT(XENON_FORMAT_DXT3A_1111),

    XENON_FORMAT_DXT4                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_DXT4_5, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT4             = MAKELINFMT(XENON_FORMAT_DXT4),

    XENON_FORMAT_DXT5                 = XENON_FORMAT_DXT4,
    XENON_FORMAT_LIN_DXT5             = MAKELINFMT(XENON_FORMAT_DXT5),

    XENON_FORMAT_DXT5A                = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_DXT5A, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT5A            = MAKELINFMT(XENON_FORMAT_DXT5A),

    XENON_FORMAT_DXN                  = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_DXN, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXN              = MAKELINFMT(XENON_FORMAT_DXN),

    XENON_FORMAT_CTX1                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_CTX1, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_CTX1             = MAKELINFMT(XENON_FORMAT_CTX1),

    // 8bpp:

    XENON_FORMAT_A8                   = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_RZZZ),
    XENON_FORMAT_LIN_A8               = MAKELINFMT(XENON_FORMAT_A8),

    XENON_FORMAT_L8                   = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORRR),
    XENON_FORMAT_LIN_L8               = MAKELINFMT(XENON_FORMAT_L8),

    // 16bpp:

    XENON_FORMAT_R5G6B5               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_5_6_5, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R5G6B5           = MAKELINFMT(XENON_FORMAT_R5G6B5),

    XENON_FORMAT_R6G5B5               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_6_5_5, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R6G5B5           = MAKELINFMT(XENON_FORMAT_R6G5B5),

    XENON_FORMAT_L6V5U5               = MAKEXENON_FORMAT2(GPUTEXTUREFORMAT_6_5_5, GPUENDIAN_8IN16, 1, GPUSIGN_SIGNED, GPUSIGN_SIGNED, GPUSIGN_UNSIGNED, GPUSIGN_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_X, GPUSWIZZLE_Y, GPUSWIZZLE_Z, GPUSWIZZLE_1),
    XENON_FORMAT_LIN_L6V5U5           = MAKELINFMT(XENON_FORMAT_L6V5U5),

    XENON_FORMAT_X1R5G5B5             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_1_5_5_5, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X1R5G5B5         = MAKELINFMT(XENON_FORMAT_X1R5G5B5),

    XENON_FORMAT_A1R5G5B5             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_1_5_5_5, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A1R5G5B5         = MAKELINFMT(XENON_FORMAT_A1R5G5B5),

    XENON_FORMAT_A4R4G4B4             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_4_4_4_4, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A4R4G4B4         = MAKELINFMT(XENON_FORMAT_A4R4G4B4),

    XENON_FORMAT_X4R4G4B4             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_4_4_4_4, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X4R4G4B4         = MAKELINFMT(XENON_FORMAT_X4R4G4B4),

    XENON_FORMAT_Q4W4V4U4             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_4_4_4_4, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q4W4V4U4         = MAKELINFMT(XENON_FORMAT_Q4W4V4U4),

    XENON_FORMAT_A8L8                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_GRRR),
    XENON_FORMAT_LIN_A8L8             = MAKELINFMT(XENON_FORMAT_A8L8),

    XENON_FORMAT_G8R8                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G8R8             = MAKELINFMT(XENON_FORMAT_G8R8),

    XENON_FORMAT_V8U8                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_V8U8             = MAKELINFMT(XENON_FORMAT_V8U8),

    XENON_FORMAT_D16                  = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_D16              = MAKELINFMT(XENON_FORMAT_D16),

    XENON_FORMAT_L16                  = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORRR),
    XENON_FORMAT_LIN_L16              = MAKELINFMT(XENON_FORMAT_L16),

    XENON_FORMAT_R16F                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_FLOAT, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_R16F             = MAKELINFMT(XENON_FORMAT_R16F),

    XENON_FORMAT_R16F_EXPAND          = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_EXPAND, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_R16F_EXPAND      = MAKELINFMT(XENON_FORMAT_R16F_EXPAND),

    XENON_FORMAT_UYVY                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_UYVY             = MAKELINFMT(XENON_FORMAT_UYVY),

    XENON_FORMAT_LE_UYVY              = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LE_LIN_UYVY          = MAKELINFMT(XENON_FORMAT_LE_UYVY),

    XENON_FORMAT_G8R8_G8B8            = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_G8R8_G8B8        = MAKELINFMT(XENON_FORMAT_G8R8_G8B8),

    XENON_FORMAT_R8G8_B8G8            = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_R8G8_B8G8        = MAKELINFMT(XENON_FORMAT_R8G8_B8G8),

    XENON_FORMAT_YUY2                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_YUY2             = MAKELINFMT(XENON_FORMAT_YUY2),

    XENON_FORMAT_LE_YUY2              = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LE_LIN_YUY2          = MAKELINFMT(XENON_FORMAT_LE_YUY2),

    // 32bpp:

    XENON_FORMAT_A8R8G8B8             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A8R8G8B8         = MAKELINFMT(XENON_FORMAT_A8R8G8B8),

    XENON_FORMAT_X8R8G8B8             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X8R8G8B8         = MAKELINFMT(XENON_FORMAT_X8R8G8B8),

    XENON_FORMAT_A8B8G8R8             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A8B8G8R8         = MAKELINFMT(XENON_FORMAT_A8B8G8R8),

    XENON_FORMAT_X8B8G8R8             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OBGR),
    XENON_FORMAT_LIN_X8B8G8R8         = MAKELINFMT(XENON_FORMAT_X8B8G8R8),

    XENON_FORMAT_X8L8V8U8             = MAKEXENON_FORMAT2(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_8IN32, 1, GPUSIGN_SIGNED, GPUSIGN_SIGNED, GPUSIGN_UNSIGNED, GPUSIGN_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_X, GPUSWIZZLE_Y, GPUSWIZZLE_Z, GPUSWIZZLE_1),
    XENON_FORMAT_LIN_X8L8V8U8         = MAKELINFMT(XENON_FORMAT_X8L8V8U8),

    XENON_FORMAT_Q8W8V8U8             = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q8W8V8U8         = MAKELINFMT(XENON_FORMAT_Q8W8V8U8),

    XENON_FORMAT_A2R10G10B10          = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A2R10G10B10      = MAKELINFMT(XENON_FORMAT_A2R10G10B10),

    XENON_FORMAT_X2R10G10B10          = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X2R10G10B10      = MAKELINFMT(XENON_FORMAT_X2R10G10B10),

    XENON_FORMAT_A2B10G10R10          = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A2B10G10R10      = MAKELINFMT(XENON_FORMAT_A2B10G10R10),

    XENON_FORMAT_A2W10V10U10          = MAKEXENON_FORMAT2(GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_SIGNED, GPUSIGN_SIGNED, GPUSIGN_SIGNED, GPUSIGN_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_X, GPUSWIZZLE_Y, GPUSWIZZLE_Z, GPUSWIZZLE_W),
    XENON_FORMAT_LIN_A2W10V10U10      = MAKELINFMT(XENON_FORMAT_A2W10V10U10),

    XENON_FORMAT_A16L16               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_GRRR),
    XENON_FORMAT_LIN_A16L16           = MAKELINFMT(XENON_FORMAT_A16L16),

    XENON_FORMAT_G16R16               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G16R16           = MAKELINFMT(XENON_FORMAT_G16R16),

    XENON_FORMAT_V16U16               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_V16U16           = MAKELINFMT(XENON_FORMAT_V16U16),

    XENON_FORMAT_R10G11B11            = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_10_11_11_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R10G11B11        = MAKELINFMT(XENON_FORMAT_R10G11B11),

    XENON_FORMAT_R11G11B10            = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_11_11_10_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R11G11B10        = MAKELINFMT(XENON_FORMAT_R11G11B10),

    XENON_FORMAT_W10V11U11            = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_10_11_11_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OBGR),
    XENON_FORMAT_LIN_W10V11U11        = MAKELINFMT(XENON_FORMAT_W10V11U11),

    XENON_FORMAT_W11V11U10            = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_11_11_10_AS_16_16_16_16, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OBGR),
    XENON_FORMAT_LIN_W11V11U10        = MAKELINFMT(XENON_FORMAT_W11V11U10),

    XENON_FORMAT_G16R16F              = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_FLOAT, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G16R16F          = MAKELINFMT(XENON_FORMAT_G16R16F),

    XENON_FORMAT_G16R16F_EXPAND       = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_EXPAND, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G16R16F_EXPAND   = MAKELINFMT(XENON_FORMAT_G16R16F_EXPAND),

    XENON_FORMAT_L32                  = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORRR),
    XENON_FORMAT_LIN_L32              = MAKELINFMT(XENON_FORMAT_L32),

    XENON_FORMAT_R32F                 = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_FLOAT, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_R32F             = MAKELINFMT(XENON_FORMAT_R32F),

    XENON_FORMAT_D24S8                = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_24_8, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_D24S8            = MAKELINFMT(XENON_FORMAT_D24S8),

    XENON_FORMAT_D24X8                = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_24_8, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_D24X8            = MAKELINFMT(XENON_FORMAT_D24X8),

    XENON_FORMAT_D24FS8               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_24_8_FLOAT, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_D24FS8           = MAKELINFMT(XENON_FORMAT_D24FS8),

    XENON_FORMAT_D32                  = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_D32              = MAKELINFMT(XENON_FORMAT_D32),

    // 64bpp:

    XENON_FORMAT_A16B16G16R16         = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_16_16, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A16B16G16R16     = MAKELINFMT(XENON_FORMAT_A16B16G16R16),

    XENON_FORMAT_Q16W16V16U16         = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_16_16, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q16W16V16U16     = MAKELINFMT(XENON_FORMAT_Q16W16V16U16),

    XENON_FORMAT_A16B16G16R16F        = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_16_16_FLOAT, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A16B16G16R16F    = MAKELINFMT(XENON_FORMAT_A16B16G16R16F),

    XENON_FORMAT_A16B16G16R16F_EXPAND = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_16_16_EXPAND, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A16B16G16R16F_EXPAND = MAKELINFMT(XENON_FORMAT_A16B16G16R16F_EXPAND),

    XENON_FORMAT_A32L32               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_32, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_GRRR),
    XENON_FORMAT_LIN_A32L32           = MAKELINFMT(XENON_FORMAT_A32L32),

    XENON_FORMAT_G32R32               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_32, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G32R32           = MAKELINFMT(XENON_FORMAT_G32R32),

    XENON_FORMAT_V32U32               = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_32, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_V32U32           = MAKELINFMT(XENON_FORMAT_V32U32),

    XENON_FORMAT_G32R32F              = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_32_FLOAT, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G32R32F          = MAKELINFMT(XENON_FORMAT_G32R32F),

    // 128bpp:

    XENON_FORMAT_A32B32G32R32         = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_32_32_32, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A32B32G32R32     = MAKELINFMT(XENON_FORMAT_A32B32G32R32),

    XENON_FORMAT_Q32W32V32U32         = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_32_32_32, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q32W32V32U32     = MAKELINFMT(XENON_FORMAT_Q32W32V32U32),

    XENON_FORMAT_A32B32G32R32F        = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_32_32_32_32_FLOAT, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A32B32G32R32F    = MAKELINFMT(XENON_FORMAT_A32B32G32R32F),

    // EDRAM only:

    XENON_FORMAT_A2B10G10R10F_EDRAM   = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_2_10_10_10_FLOAT_EDRAM, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_INTEGER, GPUSWIZZLE_ABGR),
    XENON_FORMAT_G16R16_EDRAM         = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_EDRAM, GPUENDIAN_8IN32, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_OOGR),
    XENON_FORMAT_A16B16G16R16_EDRAM   = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_16_16_16_16_EDRAM, GPUENDIAN_8IN16, 1, GPUSIGN_ALL_SIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ABGR),

    // Front buffer formats have to be little endian:

    XENON_FORMAT_LE_X8R8G8B8          = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LE_A8R8G8B8          = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_8_8_8_8, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),
    XENON_FORMAT_LE_X2R10G10B10       = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ORGB),
    XENON_FORMAT_LE_A2R10G10B10       = MAKEXENON_FORMAT(GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, GPUENDIAN_NONE, 1, GPUSIGN_ALL_UNSIGNED, GPUNUMFORMAT_FRACTION, GPUSWIZZLE_ARGB),

    // Other:

    XENON_FORMAT_INDEX16              = MAKEINDEXFMT(0, GPUENDIAN_8IN16),
    XENON_FORMAT_INDEX32              = MAKEINDEXFMT(1, GPUENDIAN_8IN32),
    XENON_FORMAT_LE_INDEX16           = MAKEINDEXFMT(0, GPUENDIAN_NONE),
    XENON_FORMAT_LE_INDEX32           = MAKEINDEXFMT(1, GPUENDIAN_NONE),

    XENON_FORMAT_VERTEXDATA           = 8,

    XENON_FORMAT_UNKNOWN              = 0xffffffff,

    // The following are not supported on Xbox 360:
    //
    // XENON_FORMAT_A8R3G3B2
    // XENON_FORMAT_R3G3B2
    // XENON_FORMAT_S1D15
    // XENON_FORMAT_S8D24
    // XENON_FORMAT_X8D24
    // XENON_FORMAT_X4S4D24
    // XENON_FORMAT_A8P8
    // XENON_FORMAT_P8
    // XENON_FORMAT_A4L4
    // XENON_FORMAT_R8G8B8
    // XENON_FORMAT_D16_LOCKABLE
    // XENON_FORMAT_D15S1
    // XENON_FORMAT_D24X4S4
    // XENON_FORMAT_D32F_LOCKABLE

    XENON_FORMAT_FORCE_DWORD          =0x7fffffff
} XENON_FORMAT;

// *****************************************************************************
//                                     EOF
// *****************************************************************************
#endif // __GN_GFX_XENONFORMAT_H__
