Import( 'GN' )

objects = []
objects.append( SConscript( 'base/makefile.scons' ) )
objects.append( SConscript( 'input/makefile.scons' ) )
objects.append( SConscript( 'win/makefile.scons' ) )
GN.NewTarget( 'GNbaseObjects', objects )
GN.NewTarget( 'GNbaseLib', GN.BuildLib( 'GNbase', objects ) )
