env = Environment()
if 'cl' == env['CC']:
    env['PCH']=env.PCH('pch.cpp')[0]
    env['PCHSTOP']='pch.h'
    env['CPPFLAGS']=['/Od', '/Zi']
    foo1 = env.Library('foo1.cpp')
    foo2 = env.Library('foo2.cpp')
    foo3 = env.Library(target='foo3', source=[foo1, foo2])
    env.Program(target='hello', source=['hello.cpp', foo3])
else:
    env.Program(target='hello', source=['hello.cpp', 'foo1.cpp', 'foo2.cpp'])
