Import( 'GN' )
sources = [
	'd3d11Buffer.cpp',
	'd3d11CapsMgr.cpp',
	'd3d11ContextMgr.cpp',
	'd3d11DispMgr.cpp',
	'd3d11DrawMgr.cpp',
	#'d3d11GpuProgram.cpp',
	'd3d11IdxBuf.cpp',
	'd3d11Renderer.cpp',
	'd3d11Resource.cpp',
	'd3d11ResourceManager.cpp',
	#'d3d11RenderTargetMgr.cpp',
	#'d3d11ShaderHlsl.cpp',
	#'d3d11StateObject.cpp',
	'd3d11Texture.cpp',
	'd3d11VtxBuf.cpp',
	'd3d11VtxLayout.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
GN.newTarget( 'shlib', 'GNrndrD3D11', [cluster], dependencies = ['GNrndrCommon'] )
