Import( 'GN' )
sources = [
	'oglCapsMgr.cpp',
	'oglContextMgr.cpp',
    'oglDispMgrMsw.cpp',
    'oglDispMgrX11.cpp',
    'oglDrawMgr.cpp',
    'oglIdxBuf.cpp',
    'oglLine.cpp',
    'oglProgramGLSL.cpp',
    'oglRenderer.cpp',
    'oglRenderTargetMgrCopyFrame.cpp',
	'oglResource.cpp',
    'oglResourceMgr.cpp',
    'oglTexture.cpp',
    'oglVtxBufNormal.cpp',
    'oglVtxBufVBO.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
target = GN.newTarget( 'shlib', 'GNrndrOGL', [cluster], dependencies = ['GNrndrCommon'] )
if GN.conf['has_cg_ogl'] :
    cluster.addCompileFlags( CPPDEFINES = ['HAS_CG=1','HAS_CG_OGL=1'] )
    target.externalDependencies += ['cgGL']
