Import( 'GN' )
sources = [
    'oglDispMgrMsw.cpp',
    'oglDispMgrX11.cpp',
    'oglRenderer.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
target = GN.newTarget( 'shlib', 'GNrndrOGL', [cluster], dependencies = ['GNrndrCommon'] )
if GN.conf['has_cg_ogl'] :
    cluster.addCompileFlags( CPPDEFINES = ['HAS_CG=1','HAS_CG_OGL=1'] )
    target.externalDependencies += ['cgGL']
