SConscript( [
	# In order of dependencies
	'inc/makefile.scons',
	'base/makefile.scons',
	'gfx/makefile.scons',
	'engine/makefile.scons',
	'util/makefile.scons',
	'core/makefile.scons',
	'media/makefile.scons',
	'tool/makefile.scons',
	'test/makefile.scons',
	'doc/makefile.scons',
	] )
