Import( 'GN' )
sources = [
    'colorFormat.cpp',
    'createRenderer.cpp',
    'd3d9FormatUtils.cpp',
    'd3d9ShaderUtils.cpp',
    'effect.cpp',
    'effectFromXml.cpp',
    'fakeRenderer.cpp',
    'image.cpp',
    'imageBMP.cpp',
    'imageDDS.cpp',
    'imageJPG.cpp',
    'imagePNG.cpp',
    'imageTGA.cpp',
    'renderState.cpp',
    'shape.cpp',
    'vertex.cpp',
]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
if GN.conf['has_d3d10'] : r.addCompileFlags( CPPDEFINES = ['HAS_D3D10'] )
Return( 'r' )
