Import( 'GN' )
if GN.conf['has_d3d9']:
    cluster = GN.newSourceCluster( ['main.cpp','orientationBox.cpp','viewfrustum.cpp'], 'pch.h', 'pch.cpp' )
    GN.newTarget( 'prog', 'GNsampleThickLine', [cluster] )
