# build static graphics library
Import( 'GN' )
sources = []
sources.append( SConscript( 'base/SConscript' ) )
GN.newTarget( 'stlib', 'GNgfx', sources )

# build renderers
SConscript( 'rndr/SConscript' )
