// Define call ID for all D3D11 and DXGI methods.
#pragma once

enum D3D11_CALL_ID
{
    // CID for ID3D11Device
    CID_ID3D11DEVICE_BASE,
    CID_ID3D11DEVICE_COUNT = 40,
    CID_ID3D11DEVICE_AddRef = CID_ID3D11DEVICE_BASE,
    CID_ID3D11DEVICE_Release,
    CID_ID3D11DEVICE_QueryInterface,
    CID_ID3D11Device_CreateBuffer,
    CID_ID3D11Device_CreateTexture1D,
    CID_ID3D11Device_CreateTexture2D,
    CID_ID3D11Device_CreateTexture3D,
    CID_ID3D11Device_CreateShaderResourceView,
    CID_ID3D11Device_CreateUnorderedAccessView,
    CID_ID3D11Device_CreateRenderTargetView,
    CID_ID3D11Device_CreateDepthStencilView,
    CID_ID3D11Device_CreateInputLayout,
    CID_ID3D11Device_CreateVertexShader,
    CID_ID3D11Device_CreateGeometryShader,
    CID_ID3D11Device_CreateGeometryShaderWithStreamOutput,
    CID_ID3D11Device_CreatePixelShader,
    CID_ID3D11Device_CreateHullShader,
    CID_ID3D11Device_CreateDomainShader,
    CID_ID3D11Device_CreateComputeShader,
    CID_ID3D11Device_CreateClassLinkage,
    CID_ID3D11Device_CreateBlendState,
    CID_ID3D11Device_CreateDepthStencilState,
    CID_ID3D11Device_CreateRasterizerState,
    CID_ID3D11Device_CreateSamplerState,
    CID_ID3D11Device_CreateQuery,
    CID_ID3D11Device_CreatePredicate,
    CID_ID3D11Device_CreateCounter,
    CID_ID3D11Device_CreateDeferredContext,
    CID_ID3D11Device_OpenSharedResource,
    CID_ID3D11Device_CheckFormatSupport,
    CID_ID3D11Device_CheckMultisampleQualityLevels,
    CID_ID3D11Device_CheckCounterInfo,
    CID_ID3D11Device_CheckCounter,
    CID_ID3D11Device_CheckFeatureSupport,
    CID_ID3D11Device_GetPrivateData,
    CID_ID3D11Device_SetPrivateData,
    CID_ID3D11Device_SetPrivateDataInterface,
    CID_ID3D11Device_GetFeatureLevel,
    CID_ID3D11Device_GetCreationFlags,
    CID_ID3D11Device_GetDeviceRemovedReason,
    CID_ID3D11Device_GetImmediateContext,
    CID_ID3D11Device_SetExceptionMode,
    CID_ID3D11Device_GetExceptionMode,
};
