// DO NOT EDIT. Generated by "gencmd.cmd"
//

namespace GN { namespace gfx
{

///
/// Renderer command enumerations.
///
enum RndrCommand {
CMD_DESTROY,///< destroy the renderer
CMD_GET_RENDERER_OPTIONS,
CMD_GET_DISP_DESC,
CMD_GET_D3D_DEVICE,
CMD_GET_OGL_RC,
CMD_GET_CAPS,
CMD_CHECK_TEXTURE_FORMAT_SUPPORT,
};
}} // end of file

