Import( 'GN' )

sources = [
	'mtidxbuf.cpp',
	'mtrndr.cpp',
	'mtrndrCmd.cpp',
	'mtshader.cpp',
	'mttexture.cpp',
	'mtvtxbuf.cpp',
	'ringbuffer.cpp',
	'rndrCreator.cpp',
]

cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'cluster' )
