Import( 'env GN_conf' )

env = env.Copy()

if GN_conf['has_xinput'] : env.Append( CPPDEFINES = ['HAS_XINPUT'] )

objs = env.GN_build_static_objects(
    env.GN_glob('*.cpp'),
    'pch.h',
    'pch.cpp',
    'GNbase.pdb' )

Return( 'objs' )
