Import( 'env GN_targets GN_func GN_conf' )

env = env.Copy()
env.Append( CPPDEFINES = ['_GN_CORE'] )

core = env.GN_build_shared_library(
    'GnCore',
    GN_func['glob']('*.cpp'),
    'pch.h',
    'pch.cpp',
    addToTargetList=0 )

if GN_conf['static'] or 'posix' == env['PLATFORM']:
    GN_targets['GnCoreLib'] = core
elif 'win32' == env['PLATFORM']:
    GN_targets['GnCoreBin'] = [ core[0], core[1] ]
    GN_targets['GnCoreLib'] = [ core[2], core[3] ]
elif 'cygwin' == env['PLATFORM']:
    GN_targets['GnCoreBin'] = core
    GN_targets['GnCoreLib'] = core
else:
    GN_func['error']( 'Unsupport platform: %s'%env['PLATFORM'] )
    Exit(-1)
