Import( 'GN' )

sources = [
	'Common.cxx',
	'DrawScene.cxx',
	'GetPosition.cxx',
	'GlFunctions.cxx',
	'InitScene.cxx',
	'main.cxx',
	'SetCamera.cxx',
	'targa.cxx',
]

if GN.conf['has_glut'] and GN.conf['has_fbx'] :
	cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
	t = GN.newTarget( 'prog', 'GNtestFbx', [cluster] )
	t.externalDependencies = [ GN.conf['glut'] ] + GN.conf['fbx_libs']
