Import( 'GN' )
sources = [
    'basicDispMgrMsw.cpp',
    'basicDispMgrX11.cpp',
    'basicRenderer.cpp',
    'basicSurface.cpp',
    'cgShader.cpp',
    'renderWindowMsw.cpp',
    'renderWindowX11.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
target = GN.newTarget( 'stlib', 'GNrndrCommon', [cluster] )
if GN.conf['has_cg'] :
    cluster.addCompileFlags( CPPDEFINES = ['HAS_CG=1'] )
    target.externalDependencies += ['cg']