Import( 'GN' )
sources = [
    'colorFormat.cpp',
    'image.cpp',
    'imageBMP.cpp',
    'imageDDS.cpp',
    'imageJPG.cpp',
    'imagePNG.cpp',
    'imageTGA.cpp',
    'shape.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'cluster' )
