Import( 'GN' )

import os.path

env = GN.NewBuildEnv()

# Gather media files
sources = GN.Glob( '*.*', True )

# Copy media files to media folder
targets = GN.PlaceSubTree( 'media', '.', sources )

# Deploy to console.
'''for x in targets:
	subfolder = os.path.dirname( GN.RelativePath( x.srcnode().path, Dir('.').path ) )
	GN.CopyToDevkit( subfolder, x )'''

# Create media build target.
GN.NewTarget( 'GNmedia', targets )
