SConscript( [
	# In order of dependencies
	'inc/makefile.scons',
	'core/makefile.scons',
	'media/makefile.scons',
	'tool/makefile.scons',
	'sample/makefile.scons',
	'test/makefile.scons',
	'doc/makefile.scons',
	] )
