Import( 'GN' )
sources = [
    'd3d9DepthBuffer.cpp',
    'd3d9Kernel.cpp',
    'd3d9KernelPort.cpp',
    'd3d9GraphicsSystem.cpp',
    'd3d9HlslKernel.cpp',
    'd3d9IdxBuf.cpp',
    'd3d9VtxBuf.cpp',
    'd3d9VtxDecl.cpp',
    'd3d9Texture.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
target = GN.newTarget( 'shlib', 'GNgfx2D3D9', [cluster], dependencies = ['GNgfx2Base'] )
if GN.conf['has_cg_d3d9'] :
    cluster.addCompileFlags( CPPDEFINES = ['HAS_CG=1','HAS_CG_D3D9=1'] )
    target.externalDependencies += ['cgD3D9']
