Import( 'GN' )
sources = [
	SConscript( 'base/SConscript' ),
	SConscript( 'gpu/SConscript' ),
	SConscript( 'gpures/SConscript' ),
	SConscript( 'misc/SConscript' )
	]
if GN.conf['has_d3d9']  : sources.append( SConscript( 'd3d9/SConscript' ) )
if GN.conf['has_d3d10'] : sources.append( SConscript( 'd3d10/SConscript' ) )
GN.newTarget( 'stlib', 'GNgfxUtil', sources )
