Import( 'GN' )
sources = [
    'createRenderer.cpp',
    'effect.cpp',
    'effectFromXml.cpp',
    'fakeRenderer.cpp',
    'fatMesh.cpp',
    'fatMeshLoader.cpp',
    'mesh.cpp',
    'renderable.cpp',
    #'nes.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
GN.newTarget( 'stlib', 'GNgfxUtil', [cluster] )
