#if !defined(__GN_INSIDE_ENGINE2_H__)
    #error "Do not include <garnet/e2/e2.h> directly. Include <garnet/GNengine2.h> instead."
#endif

#include <type_traits>
#include <concepts>

#include <glm/gtc/quaternion.hpp> // glm::quat, glm::mat4_cast, glm::angleAxis
#include <glm/mat4x4.hpp>
#include <glm/vec3.hpp>

#define GN_E2_DEFINE_A_BEING(baseType) \
protected:                             \
    using baseType::baseType;          \
                                       \
public:                                \
    GN_API GN_REGISTER_RUNTIME_TYPE(baseType);

namespace GN::e2 {

/// Shared integer nanosecond duration used by FIZ and E2.
using fiz::UnitOfTime;

/// Base for E2 objects that need instance identity: reference counting, runtime type info,
/// and an id generated by the owning Universe through the (type, id, name)
/// constructor. Currently an alias of GN::RCRT64; kept as an e2-local name so e2 can later
/// switch to a different id width (e.g. 128-bit) by changing only this definition.
using Being = GN::RCRT64;

namespace detail {

template<typename T>
concept CompleteType = requires { sizeof(T); };

// Ref<T> appears in declarations that mention the class currently being defined
// and forward-declared E2 types, so derivation can only be checked for complete types.
template<typename T>
concept RuntimeRefTarget = (!CompleteType<T>) || (std::derived_from<T, RefCounter> && std::derived_from<T, RuntimeType>);

} // namespace detail

struct Universe;

/// Smart reference to an E2 runtime object; instance identity is not required.
template<detail::RuntimeRefTarget T>
using Ref = AutoRef<T>;

} // namespace GN::e2
