#if !defined(__GN_INSIDE_ENGINE2_H__)
    #error "Do not include <garnet/e2/e2.h> directly. Include <garnet/GNengine2.h> instead."
#endif

#include <chrono>
#include <type_traits>
#include <concepts>

#include <glm/gtc/quaternion.hpp> // glm::quat, glm::mat4_cast, glm::angleAxis
#include <glm/mat4x4.hpp>
#include <glm/vec3.hpp>

#define GN_E2_DEFINE_A_BEING(baseType) \
protected:                             \
    using baseType::baseType;          \
                                       \
public:                                \
    GN_API GN_REGISTER_RUNTIME_TYPE(baseType);

namespace GN::e2 {

template<typename T>
using ArrayBody = DynaArray<T>;

template<typename T>
using ArrayView = SafeArrayAccessor<T>;

/// Unit of time used by E2
using UnitOfTime = std::chrono::nanoseconds;

/// The very basic/root type of everything that lives in this world: reference counting,
/// runtime type info, and an id generated by the owning Universe through the (type, id, name)
/// constructor. Currently an alias of GN::RCRT64; kept as an e2-local name so e2 can later
/// switch to a different id width (e.g. 128-bit) by changing only this definition.
using Being = GN::RCRT64;

namespace detail {

template<typename T>
concept CompleteType = requires { sizeof(T); };

// Ref<T> appears in declarations that mention the class currently being defined
// and forward-declared E2 types, so derivation can only be checked for complete types.
template<typename T>
concept BeingRefTarget = (!CompleteType<T>) || std::derived_from<T, Being>;

} // namespace detail

struct Universe;

/// Smart reference to a being.
template<detail::BeingRefTarget T>
using Ref = AutoRef<T>;

/// Abstraction of host operating system, providing cross platform abstraction to Window, keyboard, mouse support.
struct OperatingDomain : Being {
    GN_E2_DEFINE_A_BEING(Being);

    struct CreateParameters {
        Universe & universe;
        StrA       caption = "Garnet engine2";
        uint32_t   width   = 1280; ///< initial client width in pixels. 0 = pick a platform default.
        uint32_t   height  = 720;  ///< initial client height in pixels. 0 = pick a platform default.
    };

    /// Create the operating-system domain (main window + event pump). Returns null on failure.
    GN_API static Ref<OperatingDomain> create(const CreateParameters &);

    /// Creates a native render surface for the given graphics-API instance handle (e.g. a
    /// VkSurfaceKHR built from a VkInstance, both passed/returned as intptr_t). Returns 0 if
    /// unsupported. The domain keeps no reference to it: ownership passes to the caller, who
    /// must pass it back to destroyRenderSurface() before the instance dies.
    virtual intptr_t createRenderSurface(intptr_t graphicsInstanceHandle) const = 0;

    /// Destroys a render surface previously returned by createRenderSurface() for the same
    /// instance. Must be called after any swapchain using the surface is destroyed and while
    /// the instance is still alive. No-op if either handle is 0.
    virtual void destroyRenderSurface(intptr_t graphicsInstanceHandle, intptr_t surfaceHandle) const = 0;

    /// Current client-area size of the main window, in pixels.
    virtual Vector2<uint32_t> clientSize() const = 0;

    /// Pump the OS event queue once. Returns false when the user has requested the
    /// application to quit (e.g. the main window was closed).
    virtual bool processEvents() = 0;
};

} // namespace GN::e2
