Import( 'GN' )
sources = [
	'asciifont.cpp',
	'bitmapFontRenderer.cpp',
	'charBitmap8x13.cpp',
	'drawable.cpp',
	'fontft2.cpp',
	'quad.cpp',
	'resource.cpp',
	]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
