Import( 'GN' )
sources = [
	'actor.cpp',
	'asciifont.cpp',
	'bitmapFont.cpp',
	'charBitmap8x13.cpp',
	'fontft2.cpp',
	'quad.cpp',
	'scene.cpp',
	]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
