Import( 'GN' )
sources = [
	'boundingVolume.cpp',
	'clock.cpp',
	'debug.cpp',
	'endian.cpp',
	'file.cpp',
	'hashmap.cpp',
	'log.cpp',
	'memory.cpp',
	'misc.cpp',
	'path.cpp',
	'profiler.cpp',
	'registry.cpp',
	'sharedLib.cpp',
	'spinloop.cpp',
	'string.cpp',
	'syncmsw.cpp',
	'threadmsw.cpp',
	'variant.cpp',
	'xml.cpp',
]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
