Import( 'GN' )
sources = [
    'boundingVolume.cpp',
    'clock.cpp',
    'debug.cpp',
    'file.cpp',
    'log.cpp',
    'memory.cpp',
    'misc.cpp',
    'path.cpp',
    'plugin.cpp',
    'profiler.cpp',
    'registry.cpp',
    'sharedLib.cpp',
    'string.cpp',
    'variant.cpp'
]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
