Import( 'GN' )
sources = [
	'drawThread.cpp',
	'effect.cpp',
	'effectFromXml.cpp',
	'mesh.cpp',
	'renderEngine.cpp',
	'resourceCache.cpp',
	'resourceLRU.cpp',
	'resourceThread.cpp',
	]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
