#ifndef __GN_GFX_XENONFORMAT_H__
#define __GN_GFX_XENONFORMAT_H__
// *****************************************************************************
/// \file
/// \brief   Xenon texture format definition
/// \author  chenli@@FAREAST (2007.8.22)
// *****************************************************************************

#ifndef MAKEFOURCC
#define MAKEFOURCC GN_MAKE_FOURCC
#endif

typedef enum
{
    XENON_GPUTEXTUREFORMAT_1_REVERSE                      = 0,
    XENON_GPUTEXTUREFORMAT_1                              = 1,
    XENON_GPUTEXTUREFORMAT_8                              = 2,
    XENON_GPUTEXTUREFORMAT_1_5_5_5                        = 3,
    XENON_GPUTEXTUREFORMAT_5_6_5                          = 4,
    XENON_GPUTEXTUREFORMAT_6_5_5                          = 5,
    XENON_GPUTEXTUREFORMAT_8_8_8_8                        = 6,
    XENON_GPUTEXTUREFORMAT_2_10_10_10                     = 7,
    XENON_GPUTEXTUREFORMAT_8_A                            = 8,
    XENON_GPUTEXTUREFORMAT_8_B                            = 9,
    XENON_GPUTEXTUREFORMAT_8_8                            = 10,
    XENON_GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP                = 11,
    XENON_GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP                = 12,
    XENON_GPUTEXTUREFORMAT_16_16_EDRAM                    = 13, // EDRAM render target only
    XENON_GPUTEXTUREFORMAT_8_8_8_8_A                      = 14,
    XENON_GPUTEXTUREFORMAT_4_4_4_4                        = 15,
    XENON_GPUTEXTUREFORMAT_10_11_11                       = 16,
    XENON_GPUTEXTUREFORMAT_11_11_10                       = 17,
    XENON_GPUTEXTUREFORMAT_DXT1                           = 18,
    XENON_GPUTEXTUREFORMAT_DXT2_3                         = 19,
    XENON_GPUTEXTUREFORMAT_DXT4_5                         = 20,
    XENON_GPUTEXTUREFORMAT_16_16_16_16_EDRAM              = 21, // EDRAM render target only
    XENON_GPUTEXTUREFORMAT_24_8                           = 22,
    XENON_GPUTEXTUREFORMAT_24_8_FLOAT                     = 23,
    XENON_GPUTEXTUREFORMAT_16                             = 24,
    XENON_GPUTEXTUREFORMAT_16_16                          = 25,
    XENON_GPUTEXTUREFORMAT_16_16_16_16                    = 26,
    XENON_GPUTEXTUREFORMAT_16_EXPAND                      = 27,
    XENON_GPUTEXTUREFORMAT_16_16_EXPAND                   = 28,
    XENON_GPUTEXTUREFORMAT_16_16_16_16_EXPAND             = 29,
    XENON_GPUTEXTUREFORMAT_16_FLOAT                       = 30,
    XENON_GPUTEXTUREFORMAT_16_16_FLOAT                    = 31,
    XENON_GPUTEXTUREFORMAT_16_16_16_16_FLOAT              = 32,
    XENON_GPUTEXTUREFORMAT_32                             = 33,
    XENON_GPUTEXTUREFORMAT_32_32                          = 34,
    XENON_GPUTEXTUREFORMAT_32_32_32_32                    = 35,
    XENON_GPUTEXTUREFORMAT_32_FLOAT                       = 36,
    XENON_GPUTEXTUREFORMAT_32_32_FLOAT                    = 37,
    XENON_GPUTEXTUREFORMAT_32_32_32_32_FLOAT              = 38,
    XENON_GPUTEXTUREFORMAT_32_AS_8                        = 39,
    XENON_GPUTEXTUREFORMAT_32_AS_8_8                      = 40,
    XENON_GPUTEXTUREFORMAT_16_MPEG                        = 41,
    XENON_GPUTEXTUREFORMAT_16_16_MPEG                     = 42,
    XENON_GPUTEXTUREFORMAT_8_INTERLACED                   = 43,
    XENON_GPUTEXTUREFORMAT_32_AS_8_INTERLACED             = 44,
    XENON_GPUTEXTUREFORMAT_32_AS_8_8_INTERLACED           = 45,
    XENON_GPUTEXTUREFORMAT_16_INTERLACED                  = 46,
    XENON_GPUTEXTUREFORMAT_16_MPEG_INTERLACED             = 47,
    XENON_GPUTEXTUREFORMAT_16_16_MPEG_INTERLACED          = 48,
    XENON_GPUTEXTUREFORMAT_DXN                            = 49,
    XENON_GPUTEXTUREFORMAT_8_8_8_8_AS_16_16_16_16         = 50,
    XENON_GPUTEXTUREFORMAT_DXT1_AS_16_16_16_16            = 51,
    XENON_GPUTEXTUREFORMAT_DXT2_3_AS_16_16_16_16          = 52,
    XENON_GPUTEXTUREFORMAT_DXT4_5_AS_16_16_16_16          = 53,
    XENON_GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16      = 54,
    XENON_GPUTEXTUREFORMAT_10_11_11_AS_16_16_16_16        = 55,
    XENON_GPUTEXTUREFORMAT_11_11_10_AS_16_16_16_16        = 56,
    XENON_GPUTEXTUREFORMAT_32_32_32_FLOAT                 = 57,
    XENON_GPUTEXTUREFORMAT_DXT3A                          = 58,
    XENON_GPUTEXTUREFORMAT_DXT5A                          = 59,
    XENON_GPUTEXTUREFORMAT_CTX1                           = 60,
    XENON_GPUTEXTUREFORMAT_DXT3A_AS_1_1_1_1               = 61,
    XENON_GPUTEXTUREFORMAT_8_8_8_8_GAMMA_EDRAM            = 62, // EDRAM render target only
    XENON_GPUTEXTUREFORMAT_2_10_10_10_FLOAT_EDRAM         = 63, // EDRAM render target only
} XENON_GPUTEXTUREFORMAT;
typedef enum
{
    XENON_GPUSIGN_UNSIGNED                                = 0,
    XENON_GPUSIGN_SIGNED                                  = 1,
    XENON_GPUSIGN_BIAS                                    = 2,
    XENON_GPUSIGN_GAMMA                                   = 3,
} XENON_GPUSIGN;

#define XENON_GPUSIGN_ALL_UNSIGNED (XENON_GPUSIGN_UNSIGNED | XENON_GPUSIGN_UNSIGNED<<2 | XENON_GPUSIGN_UNSIGNED<<4 | XENON_GPUSIGN_UNSIGNED<<6)
#define XENON_GPUSIGN_ALL_SIGNED (XENON_GPUSIGN_SIGNED | XENON_GPUSIGN_SIGNED<<2 | XENON_GPUSIGN_SIGNED<<4 | XENON_GPUSIGN_SIGNED<<6)

typedef enum
{
    XENON_GPUSWIZZLE_X                                    = 0,
    XENON_GPUSWIZZLE_Y                                    = 1,
    XENON_GPUSWIZZLE_Z                                    = 2,
    XENON_GPUSWIZZLE_W                                    = 3,
    XENON_GPUSWIZZLE_0                                    = 4,
    XENON_GPUSWIZZLE_1                                    = 5,
    XENON_GPUSWIZZLE_KEEP                                 = 7, // Fetch instructions only
} XENON_GPUSWIZZLE;

#define XENON_GPUSWIZZLE_ARGB (XENON_GPUSWIZZLE_Z | XENON_GPUSWIZZLE_Y<<3 | XENON_GPUSWIZZLE_X<<6 | XENON_GPUSWIZZLE_W<<9)
#define XENON_GPUSWIZZLE_ORGB (XENON_GPUSWIZZLE_Z | XENON_GPUSWIZZLE_Y<<3 | XENON_GPUSWIZZLE_X<<6 | XENON_GPUSWIZZLE_1<<9)
#define XENON_GPUSWIZZLE_ABGR (XENON_GPUSWIZZLE_X | XENON_GPUSWIZZLE_Y<<3 | XENON_GPUSWIZZLE_Z<<6 | XENON_GPUSWIZZLE_W<<9)
#define XENON_GPUSWIZZLE_OBGR (XENON_GPUSWIZZLE_X | XENON_GPUSWIZZLE_Y<<3 | XENON_GPUSWIZZLE_Z<<6 | XENON_GPUSWIZZLE_1<<9)
#define XENON_GPUSWIZZLE_OOGR (XENON_GPUSWIZZLE_X | XENON_GPUSWIZZLE_Y<<3 | XENON_GPUSWIZZLE_1<<6 | XENON_GPUSWIZZLE_1<<9)
#define XENON_GPUSWIZZLE_OZGR (XENON_GPUSWIZZLE_X | XENON_GPUSWIZZLE_Y<<3 | XENON_GPUSWIZZLE_0<<6 | XENON_GPUSWIZZLE_1<<9)
#define XENON_GPUSWIZZLE_RZZZ (XENON_GPUSWIZZLE_0 | XENON_GPUSWIZZLE_0<<3 | XENON_GPUSWIZZLE_0<<6 | XENON_GPUSWIZZLE_X<<9)
#define XENON_GPUSWIZZLE_OOOR (XENON_GPUSWIZZLE_X | XENON_GPUSWIZZLE_1<<3 | XENON_GPUSWIZZLE_1<<6 | XENON_GPUSWIZZLE_1<<9)
#define XENON_GPUSWIZZLE_ORRR (XENON_GPUSWIZZLE_X | XENON_GPUSWIZZLE_X<<3 | XENON_GPUSWIZZLE_X<<6 | XENON_GPUSWIZZLE_1<<9)
#define XENON_GPUSWIZZLE_GRRR (XENON_GPUSWIZZLE_X | XENON_GPUSWIZZLE_X<<3 | XENON_GPUSWIZZLE_X<<6 | XENON_GPUSWIZZLE_Y<<9)
#define XENON_GPUSWIZZLE_RGBA (XENON_GPUSWIZZLE_W | XENON_GPUSWIZZLE_Z<<3 | XENON_GPUSWIZZLE_Y<<6 | XENON_GPUSWIZZLE_X<<9)

typedef enum
{
    XENON_GPUENDIAN_NONE                                  = 0,
    XENON_GPUENDIAN_8IN16                                 = 1,
    XENON_GPUENDIAN_8IN32                                 = 2,
    XENON_GPUENDIAN_16IN32                                = 3,
} XENON_GPUENDIAN;

typedef enum
{
    XENON_GPUNUMFORMAT_FRACTION                           = 0,
    XENON_GPUNUMFORMAT_INTEGER                            = 1,
} XENON_GPUNUMFORMAT;

// A XENON_FORMAT constant is an identifier that uniquely identifies
// a texture or surface format.  It contains the following fields:

#define XENON_FORMAT_TEXTUREFORMAT_SHIFT   0       // XENON_GPUTEXTUREFORMAT
#define XENON_FORMAT_ENDIAN_SHIFT          6       // XENON_GPUENDIAN
#define XENON_FORMAT_TILED_SHIFT           8       // BOOL
#define XENON_FORMAT_SIGNX_SHIFT           9       // XENON_GPUSIGN
#define XENON_FORMAT_SIGNY_SHIFT           11      // XENON_GPUSIGN
#define XENON_FORMAT_SIGNZ_SHIFT           13      // XENON_GPUSIGN
#define XENON_FORMAT_SIGNW_SHIFT           15      // XENON_GPUSIGN
#define XENON_FORMAT_NUMFORMAT_SHIFT       17      // XENON_GPUNUMFORMAT
#define XENON_FORMAT_SWIZZLEX_SHIFT        18      // XENON_GPUSWIZZLE
#define XENON_FORMAT_SWIZZLEY_SHIFT        21      // XENON_GPUSWIZZLE
#define XENON_FORMAT_SWIZZLEZ_SHIFT        24      // XENON_GPUSWIZZLE
#define XENON_FORMAT_SWIZZLEW_SHIFT        27      // XENON_GPUSWIZZLE
#define XENON_FORMAT_SWIZZLE_SHIFT         XENON_FORMAT_SWIZZLEX_SHIFT

#define XENON_FORMAT_TEXTUREFORMAT_MASK    0x0000003f
#define XENON_FORMAT_ENDIAN_MASK           0x000000c0
#define XENON_FORMAT_TILED_MASK            0x00000100
#define XENON_FORMAT_SIGNX_MASK            0x00000600
#define XENON_FORMAT_SIGNY_MASK            0x00001800
#define XENON_FORMAT_SIGNZ_MASK            0x00006000
#define XENON_FORMAT_SIGNW_MASK            0x00018000
#define XENON_FORMAT_NUMFORMAT_MASK        0x00020000
#define XENON_FORMAT_SWIZZLEX_MASK         0x001c0000
#define XENON_FORMAT_SWIZZLEY_MASK         0x00e00000
#define XENON_FORMAT_SWIZZLEZ_MASK         0x07000000
#define XENON_FORMAT_SWIZZLEW_MASK         0x38000000
#define XENON_FORMAT_SWIZZLE_MASK          (XENON_FORMAT_SWIZZLEX_MASK | XENON_FORMAT_SWIZZLEY_MASK | XENON_FORMAT_SWIZZLEZ_MASK | XENON_FORMAT_SWIZZLEW_MASK)

#define XENON_MAKEXENON_FORMAT(TextureFormat, Endian, Tiled, TextureSign, NumFormat, Swizzle) \
            ((TextureFormat) << XENON_FORMAT_TEXTUREFORMAT_SHIFT | \
             (Endian) << XENON_FORMAT_ENDIAN_SHIFT | \
             (Tiled) << XENON_FORMAT_TILED_SHIFT | \
             (TextureSign) << XENON_FORMAT_SIGNX_SHIFT | \
             (NumFormat) << XENON_FORMAT_NUMFORMAT_SHIFT | \
             (Swizzle) << XENON_FORMAT_SWIZZLEX_SHIFT)

#define XENON_MAKEXENON_FORMAT2(TextureFormat, Endian, Tiled, TextureSignX, TextureSignY, TextureSignZ, TextureSignW, NumFormat, SwizzleX, SwizzleY, SwizzleZ, SwizzleW) \
            ((TextureFormat) << XENON_FORMAT_TEXTUREFORMAT_SHIFT | \
             (Endian) << XENON_FORMAT_ENDIAN_SHIFT | \
             (Tiled) << XENON_FORMAT_TILED_SHIFT | \
             (TextureSignX) << XENON_FORMAT_SIGNX_SHIFT | \
             (TextureSignY) << XENON_FORMAT_SIGNY_SHIFT | \
             (TextureSignZ) << XENON_FORMAT_SIGNZ_SHIFT | \
             (TextureSignW) << XENON_FORMAT_SIGNW_SHIFT | \
             (NumFormat) << XENON_FORMAT_NUMFORMAT_SHIFT | \
             (SwizzleX) << XENON_FORMAT_SWIZZLEX_SHIFT | \
             (SwizzleY) << XENON_FORMAT_SWIZZLEY_SHIFT | \
             (SwizzleZ) << XENON_FORMAT_SWIZZLEZ_SHIFT | \
             (SwizzleW) << XENON_FORMAT_SWIZZLEW_SHIFT)

#define XENON_MAKELINFMT(D3dFmt) ((D3dFmt) & ~XENON_FORMAT_TILED_MASK)

#define XENON_MAKESRGBFMT(D3dFmt) (((D3dFmt) & ~(XENON_FORMAT_SIGNX_MASK | XENON_FORMAT_SIGNY_MASK | XENON_FORMAT_SIGNZ_MASK)) | \
             ((XENON_GPUSIGN_GAMMA << XENON_FORMAT_SIGNX_SHIFT) | \
              (XENON_GPUSIGN_GAMMA << XENON_FORMAT_SIGNY_SHIFT) | \
              (XENON_GPUSIGN_GAMMA << XENON_FORMAT_SIGNZ_SHIFT)))

#define XENON_MAKELEFMT(D3dFmt) (((D3dFmt) & ~XENON_FORMAT_ENDIAN_MASK) | (XENON_GPUENDIAN_NONE << XENON_FORMAT_ENDIAN_SHIFT))

// An index XENON_FORMAT encodes the index size and endianness:

#define XENON_D3DINDEXFORMAT_ENDIAN_SHIFT     0       // XENON_GPUENDIAN
#define XENON_D3DINDEXFORMAT_32BITS_SHIFT     2       // BOOL

#define XENON_D3DINDEXFORMAT_ENDIAN_MASK      0x00000003
#define XENON_D3DINDEXFORMAT_32BITS_MASK      0x00000004

#define XENON_MAKEINDEXFMT(Is32Bits, Endian) \
            ((Is32Bits) << XENON_D3DINDEXFORMAT_32BITS_SHIFT | \
             (Endian) << XENON_D3DINDEXFORMAT_ENDIAN_SHIFT)

typedef enum _XENON_FORMAT
{
    // DXT:

    XENON_FORMAT_DXT1                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_DXT1, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT1             = XENON_MAKELINFMT(XENON_FORMAT_DXT1),

    XENON_FORMAT_DXT2                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_DXT2_3, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT2             = XENON_MAKELINFMT(XENON_FORMAT_DXT2),

    XENON_FORMAT_DXT3                 = XENON_FORMAT_DXT2,
    XENON_FORMAT_LIN_DXT3             = XENON_MAKELINFMT(XENON_FORMAT_DXT3),

    XENON_FORMAT_DXT3A                = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_DXT3A, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT3A            = XENON_MAKELINFMT(XENON_FORMAT_DXT3A),

    XENON_FORMAT_DXT3A_1111           = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_DXT3A_AS_1_1_1_1, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT3A_1111       = XENON_MAKELINFMT(XENON_FORMAT_DXT3A_1111),

    XENON_FORMAT_DXT4                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_DXT4_5, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT4             = XENON_MAKELINFMT(XENON_FORMAT_DXT4),

    XENON_FORMAT_DXT5                 = XENON_FORMAT_DXT4,
    XENON_FORMAT_LIN_DXT5             = XENON_MAKELINFMT(XENON_FORMAT_DXT5),

    XENON_FORMAT_DXT5A                = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_DXT5A, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXT5A            = XENON_MAKELINFMT(XENON_FORMAT_DXT5A),

    XENON_FORMAT_DXN                  = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_DXN, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_DXN              = XENON_MAKELINFMT(XENON_FORMAT_DXN),

    XENON_FORMAT_CTX1                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_CTX1, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_CTX1             = XENON_MAKELINFMT(XENON_FORMAT_CTX1),

    // 8bpp:

    XENON_FORMAT_A8                   = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_RZZZ),
    XENON_FORMAT_LIN_A8               = XENON_MAKELINFMT(XENON_FORMAT_A8),

    XENON_FORMAT_L8                   = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORRR),
    XENON_FORMAT_LIN_L8               = XENON_MAKELINFMT(XENON_FORMAT_L8),

    // 16bpp:

    XENON_FORMAT_R5G6B5               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_5_6_5, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R5G6B5           = XENON_MAKELINFMT(XENON_FORMAT_R5G6B5),

    XENON_FORMAT_R6G5B5               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_6_5_5, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R6G5B5           = XENON_MAKELINFMT(XENON_FORMAT_R6G5B5),

    XENON_FORMAT_L6V5U5               = XENON_MAKEXENON_FORMAT2(XENON_GPUTEXTUREFORMAT_6_5_5, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_SIGNED, XENON_GPUSIGN_SIGNED, XENON_GPUSIGN_UNSIGNED, XENON_GPUSIGN_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_X, XENON_GPUSWIZZLE_Y, XENON_GPUSWIZZLE_Z, XENON_GPUSWIZZLE_1),
    XENON_FORMAT_LIN_L6V5U5           = XENON_MAKELINFMT(XENON_FORMAT_L6V5U5),

    XENON_FORMAT_X1R5G5B5             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_1_5_5_5, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X1R5G5B5         = XENON_MAKELINFMT(XENON_FORMAT_X1R5G5B5),

    XENON_FORMAT_A1R5G5B5             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_1_5_5_5, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A1R5G5B5         = XENON_MAKELINFMT(XENON_FORMAT_A1R5G5B5),

    XENON_FORMAT_A4R4G4B4             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_4_4_4_4, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A4R4G4B4         = XENON_MAKELINFMT(XENON_FORMAT_A4R4G4B4),

    XENON_FORMAT_X4R4G4B4             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_4_4_4_4, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X4R4G4B4         = XENON_MAKELINFMT(XENON_FORMAT_X4R4G4B4),

    XENON_FORMAT_Q4W4V4U4             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_4_4_4_4, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q4W4V4U4         = XENON_MAKELINFMT(XENON_FORMAT_Q4W4V4U4),

    XENON_FORMAT_A8L8                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_GRRR),
    XENON_FORMAT_LIN_A8L8             = XENON_MAKELINFMT(XENON_FORMAT_A8L8),

    XENON_FORMAT_G8R8                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G8R8             = XENON_MAKELINFMT(XENON_FORMAT_G8R8),

    XENON_FORMAT_V8U8                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_V8U8             = XENON_MAKELINFMT(XENON_FORMAT_V8U8),

    XENON_FORMAT_D16                  = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_D16              = XENON_MAKELINFMT(XENON_FORMAT_D16),

    XENON_FORMAT_L16                  = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORRR),
    XENON_FORMAT_LIN_L16              = XENON_MAKELINFMT(XENON_FORMAT_L16),

    XENON_FORMAT_R16F                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_FLOAT, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_R16F             = XENON_MAKELINFMT(XENON_FORMAT_R16F),

    XENON_FORMAT_R16F_EXPAND          = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_EXPAND, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_R16F_EXPAND      = XENON_MAKELINFMT(XENON_FORMAT_R16F_EXPAND),

    XENON_FORMAT_UYVY                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_UYVY             = XENON_MAKELINFMT(XENON_FORMAT_UYVY),

    XENON_FORMAT_LE_UYVY              = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LE_LIN_UYVY          = XENON_MAKELINFMT(XENON_FORMAT_LE_UYVY),

    XENON_FORMAT_G8R8_G8B8            = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_Y1_Cr_Y0_Cb_REP, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_G8R8_G8B8        = XENON_MAKELINFMT(XENON_FORMAT_G8R8_G8B8),

    XENON_FORMAT_R8G8_B8G8            = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_R8G8_B8G8        = XENON_MAKELINFMT(XENON_FORMAT_R8G8_B8G8),

    XENON_FORMAT_YUY2                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_YUY2             = XENON_MAKELINFMT(XENON_FORMAT_YUY2),

    XENON_FORMAT_LE_YUY2              = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_Cr_Y1_Cb_Y0_REP, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LE_LIN_YUY2          = XENON_MAKELINFMT(XENON_FORMAT_LE_YUY2),

    // 32bpp:

    XENON_FORMAT_A8R8G8B8             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A8R8G8B8         = XENON_MAKELINFMT(XENON_FORMAT_A8R8G8B8),

    XENON_FORMAT_X8R8G8B8             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X8R8G8B8         = XENON_MAKELINFMT(XENON_FORMAT_X8R8G8B8),

    XENON_FORMAT_A8B8G8R8             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A8B8G8R8         = XENON_MAKELINFMT(XENON_FORMAT_A8B8G8R8),

    XENON_FORMAT_X8B8G8R8             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OBGR),
    XENON_FORMAT_LIN_X8B8G8R8         = XENON_MAKELINFMT(XENON_FORMAT_X8B8G8R8),

    XENON_FORMAT_X8L8V8U8             = XENON_MAKEXENON_FORMAT2(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_SIGNED, XENON_GPUSIGN_SIGNED, XENON_GPUSIGN_UNSIGNED, XENON_GPUSIGN_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_X, XENON_GPUSWIZZLE_Y, XENON_GPUSWIZZLE_Z, XENON_GPUSWIZZLE_1),
    XENON_FORMAT_LIN_X8L8V8U8         = XENON_MAKELINFMT(XENON_FORMAT_X8L8V8U8),

    XENON_FORMAT_Q8W8V8U8             = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q8W8V8U8         = XENON_MAKELINFMT(XENON_FORMAT_Q8W8V8U8),

    XENON_FORMAT_A2R10G10B10          = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),
    XENON_FORMAT_LIN_A2R10G10B10      = XENON_MAKELINFMT(XENON_FORMAT_A2R10G10B10),

    XENON_FORMAT_X2R10G10B10          = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_X2R10G10B10      = XENON_MAKELINFMT(XENON_FORMAT_X2R10G10B10),

    XENON_FORMAT_A2B10G10R10          = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A2B10G10R10      = XENON_MAKELINFMT(XENON_FORMAT_A2B10G10R10),

    XENON_FORMAT_A2W10V10U10          = XENON_MAKEXENON_FORMAT2(XENON_GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_SIGNED, XENON_GPUSIGN_SIGNED, XENON_GPUSIGN_SIGNED, XENON_GPUSIGN_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_X, XENON_GPUSWIZZLE_Y, XENON_GPUSWIZZLE_Z, XENON_GPUSWIZZLE_W),
    XENON_FORMAT_LIN_A2W10V10U10      = XENON_MAKELINFMT(XENON_FORMAT_A2W10V10U10),

    XENON_FORMAT_A16L16               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_GRRR),
    XENON_FORMAT_LIN_A16L16           = XENON_MAKELINFMT(XENON_FORMAT_A16L16),

    XENON_FORMAT_G16R16               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G16R16           = XENON_MAKELINFMT(XENON_FORMAT_G16R16),

    XENON_FORMAT_V16U16               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_V16U16           = XENON_MAKELINFMT(XENON_FORMAT_V16U16),

    XENON_FORMAT_R10G11B11            = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_10_11_11_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R10G11B11        = XENON_MAKELINFMT(XENON_FORMAT_R10G11B11),

    XENON_FORMAT_R11G11B10            = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_11_11_10_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LIN_R11G11B10        = XENON_MAKELINFMT(XENON_FORMAT_R11G11B10),

    XENON_FORMAT_W10V11U11            = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_10_11_11_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OBGR),
    XENON_FORMAT_LIN_W10V11U11        = XENON_MAKELINFMT(XENON_FORMAT_W10V11U11),

    XENON_FORMAT_W11V11U10            = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_11_11_10_AS_16_16_16_16, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OBGR),
    XENON_FORMAT_LIN_W11V11U10        = XENON_MAKELINFMT(XENON_FORMAT_W11V11U10),

    XENON_FORMAT_G16R16F              = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_FLOAT, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G16R16F          = XENON_MAKELINFMT(XENON_FORMAT_G16R16F),

    XENON_FORMAT_G16R16F_EXPAND       = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_EXPAND, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G16R16F_EXPAND   = XENON_MAKELINFMT(XENON_FORMAT_G16R16F_EXPAND),

    XENON_FORMAT_L32                  = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORRR),
    XENON_FORMAT_LIN_L32              = XENON_MAKELINFMT(XENON_FORMAT_L32),

    XENON_FORMAT_R32F                 = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_FLOAT, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_R32F             = XENON_MAKELINFMT(XENON_FORMAT_R32F),

    XENON_FORMAT_D24S8                = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_24_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_D24S8            = XENON_MAKELINFMT(XENON_FORMAT_D24S8),

    XENON_FORMAT_D24X8                = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_24_8, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOOR),
    XENON_FORMAT_LIN_D24X8            = XENON_MAKELINFMT(XENON_FORMAT_D24X8),

    XENON_FORMAT_D24FS8               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_24_8_FLOAT, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_D24FS8           = XENON_MAKELINFMT(XENON_FORMAT_D24FS8),

    XENON_FORMAT_D32                  = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_D32              = XENON_MAKELINFMT(XENON_FORMAT_D32),

    // 64bpp:

    XENON_FORMAT_A16B16G16R16         = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_16_16, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A16B16G16R16     = XENON_MAKELINFMT(XENON_FORMAT_A16B16G16R16),

    XENON_FORMAT_Q16W16V16U16         = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_16_16, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q16W16V16U16     = XENON_MAKELINFMT(XENON_FORMAT_Q16W16V16U16),

    XENON_FORMAT_A16B16G16R16F        = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_16_16_FLOAT, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A16B16G16R16F    = XENON_MAKELINFMT(XENON_FORMAT_A16B16G16R16F),

    XENON_FORMAT_A16B16G16R16F_EXPAND = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_16_16_EXPAND, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A16B16G16R16F_EXPAND = XENON_MAKELINFMT(XENON_FORMAT_A16B16G16R16F_EXPAND),

    XENON_FORMAT_A32L32               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_32, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_GRRR),
    XENON_FORMAT_LIN_A32L32           = XENON_MAKELINFMT(XENON_FORMAT_A32L32),

    XENON_FORMAT_G32R32               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_32, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G32R32           = XENON_MAKELINFMT(XENON_FORMAT_G32R32),

    XENON_FORMAT_V32U32               = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_32, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_V32U32           = XENON_MAKELINFMT(XENON_FORMAT_V32U32),

    XENON_FORMAT_G32R32F              = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_32_FLOAT, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_LIN_G32R32F          = XENON_MAKELINFMT(XENON_FORMAT_G32R32F),

    // 128bpp:

    XENON_FORMAT_A32B32G32R32         = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_32_32_32, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A32B32G32R32     = XENON_MAKELINFMT(XENON_FORMAT_A32B32G32R32),

    XENON_FORMAT_Q32W32V32U32         = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_32_32_32, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_Q32W32V32U32     = XENON_MAKELINFMT(XENON_FORMAT_Q32W32V32U32),

    XENON_FORMAT_A32B32G32R32F        = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_32_32_32_32_FLOAT, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_LIN_A32B32G32R32F    = XENON_MAKELINFMT(XENON_FORMAT_A32B32G32R32F),

    // EDRAM only:

    XENON_FORMAT_A2B10G10R10F_EDRAM   = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_2_10_10_10_FLOAT_EDRAM, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_INTEGER, XENON_GPUSWIZZLE_ABGR),
    XENON_FORMAT_G16R16_EDRAM         = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_EDRAM, XENON_GPUENDIAN_8IN32, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_OOGR),
    XENON_FORMAT_A16B16G16R16_EDRAM   = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_16_16_16_16_EDRAM, XENON_GPUENDIAN_8IN16, 1, XENON_GPUSIGN_ALL_SIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ABGR),

    // Front buffer formats have to be little endian:

    XENON_FORMAT_LE_X8R8G8B8          = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LE_A8R8G8B8          = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_8_8_8_8, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),
    XENON_FORMAT_LE_X2R10G10B10       = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ORGB),
    XENON_FORMAT_LE_A2R10G10B10       = XENON_MAKEXENON_FORMAT(XENON_GPUTEXTUREFORMAT_2_10_10_10_AS_16_16_16_16, XENON_GPUENDIAN_NONE, 1, XENON_GPUSIGN_ALL_UNSIGNED, XENON_GPUNUMFORMAT_FRACTION, XENON_GPUSWIZZLE_ARGB),

    // Other:

    XENON_FORMAT_INDEX16              = XENON_MAKEINDEXFMT(0, XENON_GPUENDIAN_8IN16),
    XENON_FORMAT_INDEX32              = XENON_MAKEINDEXFMT(1, XENON_GPUENDIAN_8IN32),
    XENON_FORMAT_LE_INDEX16           = XENON_MAKEINDEXFMT(0, XENON_GPUENDIAN_NONE),
    XENON_FORMAT_LE_INDEX32           = XENON_MAKEINDEXFMT(1, XENON_GPUENDIAN_NONE),

    XENON_FORMAT_VERTEXDATA           = 8,

    XENON_FORMAT_UNKNOWN              = 0xffffffff,

    // The following are not supported on Xbox 360:
    //
    // XENON_FORMAT_A8R3G3B2
    // XENON_FORMAT_R3G3B2
    // XENON_FORMAT_S1D15
    // XENON_FORMAT_S8D24
    // XENON_FORMAT_X8D24
    // XENON_FORMAT_X4S4D24
    // XENON_FORMAT_A8P8
    // XENON_FORMAT_P8
    // XENON_FORMAT_A4L4
    // XENON_FORMAT_R8G8B8
    // XENON_FORMAT_D16_LOCKABLE
    // XENON_FORMAT_D15S1
    // XENON_FORMAT_D24X4S4
    // XENON_FORMAT_D32F_LOCKABLE

    XENON_FORMAT_FORCE_DWORD          =0x7fffffff
} XENON_FORMAT;

// *****************************************************************************
//                                     EOF
// *****************************************************************************
#endif // __GN_GFX_XENONFORMAT_H__
