Import( 'env GN_targets GN_func' )

if 'win32' == env['PLATFORM']:
    env.GN_build_static_library(
        'GNd3d',
        GN_func['glob']('*.cpp'),
        'pch.h',
        'pch.cpp' )
    SConscript( 'test/SConscript' )