Import( 'GN' )

sources = [
	'engine_base.cpp',
	'skinned_mesh.cpp',
	'static_mesh.cpp',
	'spacial_component.cpp',
    'visual_component.cpp',
]
objects = GN.BuildObjects( None, sources, 'pch.h', 'pch.cpp' )
GN.NewTarget( 'GNengineObjects', objects )
GN.NewTarget( 'GNengineLib', GN.BuildLib( None, 'GNutil', objects ) )
