Import( 'GN' )

sources = [
	'engine_base.cpp',
	'spacial_component.cpp',
    'visual_component.cpp',
]

cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
GN.newTarget( 'stlib', 'GNengine', [cluster] )
