Import( 'GN' )
sources = [
    'colorFormat.cpp',
    'createRenderer.cpp',
    'd3d9FormatUtils.cpp',
    'd3d9ShaderUtils.cpp',
    'd3d10FormatUtils.cpp',
    'effect.cpp',
    'effectFromXml.cpp',
    'fakeRenderer.cpp',
    'fatMesh.cpp',
    'fatMeshLoader.cpp',
    'image.cpp',
    'imageBMP.cpp',
    'imageDDS.cpp',
    'imageJPG.cpp',
    'imagePNG.cpp',
    'imageTGA.cpp',
    'renderState.cpp',
    # 'nes.cpp',
    'shape.cpp',
    'vertex.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
if GN.conf['has_d3d9'] : cluster.addCompileFlags( CPPDEFINES = ['HAS_D3D9'] )
if GN.conf['has_d3d10'] : cluster.addCompileFlags( CPPDEFINES = ['HAS_D3D10'] )
if GN.conf['has_ogl'] : cluster.addCompileFlags( CPPDEFINES = ['HAS_OGL'] )
GN.newTarget( 'stlib', 'GNgfx', [cluster] )
