sources = [
    'd3d10DispMgr.cpp',
    'd3d10DrawMgr.cpp',
    'd3d10Renderer.cpp',
]
env = Environment()
cluster = env.GN_newSourceCluster( sources, 'pch.h', 'pch.cpp' )
env.GN_newTarget( 'shlib', 'GNgfxD3D10', [cluster], dependencies = ['GNgfxCommon'] )
