Import( 'GN' )
sources = [
    'd3d10DispMgr.cpp',
    'd3d10DrawMgr.cpp',
    'd3d10Renderer.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
GN.newTarget( 'shlib', 'GNgfxD3D10', [cluster], dependencies = ['GNgfxCommon'] )
