Import( 'GN' )

dxgi_sources =[
    'dxgiTextureFormat.cpp'
]

d3d11_sources = [
    'd3d11ShaderUtils.cpp',
    'd3d11Utils.cpp',
]

sources = []
if GN.conf['has_d3d10'] or GN.conf['has_d3d11'] : sources += dxgi_sources
if GN.conf['has_d3d11']: sources += d3d11_sources

cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'cluster' )
