Import( 'GN' )

sources = [
	'cmdbuf.cpp',
	'mtidxbuf.cpp',
	'mtgpu.cpp',
	'mtgpuCmd.cpp',
	'mtshader.cpp',
	'mttexture.cpp',
	'mtvtxbuf.cpp',
	'gpuCreator.cpp',
]

cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'cluster' )
