//
// DO NOT EDIT. Generated by "gencmd.cmd"
//

namespace GN { namespace gfx
{

///
/// Gpu command enumerations.
///
enum GpuCommand {
    CMD_SHUTDOWN,
    CMD_FENCE,
    CMD_GET_GPU_OPTIONS,///< get GPU options
    CMD_GET_DISP_DESC,///< get display descriptor
    CMD_GET_D3D_DEVICE,
    CMD_GET_OGL_RC,
    CMD_GET_CAPS,
    CMD_CHECK_TEXTURE_FORMAT_SUPPORT,
    CMD_GET_DEFAULT_TEXTURE_FORMAT,
    CMD_COMPILE_GPU_PROGRAM,
    CMD_CREATE_GPU_PROGRAM,
    CMD_CREATE_UNIFORM,
    CMD_CREATE_TEXTURE,
    CMD_CREATE_VTXBUF,
    CMD_CREATE_IDXBUF,
    CMD_BIND_CONTEXT,
    CMD_REBIND_CONTEXT,
    CMD_PRESENT,
    CMD_CLEAR_SCREEN,
    CMD_DRAW_INDEXED,
    CMD_DRAW,
    CMD_DRAW_INDEXED_UP,
    CMD_DRAW_UP,
    CMD_DRAW_LINES,
    CMD_GET_BACK_BUFFER_CONTENT,
    CMD_PROCESS_RENDER_WINDOW_MESSAGES,
    CMD_ENABLE_PARAMETER_CHECK,
    CMD_DUMP_NEXT_FRAME,
    CMD_GPU_PROGRAM_DESTROY,
    CMD_GPU_PROGRAM_INIT,
    CMD_UNIFORM_DESTROY,
    CMD_UNIFORM_UPDATE,
    CMD_TEXTURE_DESTROY,
    CMD_TEXTURE_UPDATE_MIPMAP,
    CMD_TEXTURE_READ_MIPMAP,
    CMD_TEXTURE_BLOB_WRITE,
    CMD_TEXTURE_BLOB_READ,
    CMD_VTXBUF_DESTROY,
    CMD_VTXBUF_UPDATE,
    CMD_VTXBUF_READBACK,
    CMD_IDXBUF_DESTROY,
    CMD_IDXBUF_UPDATE,
    CMD_IDXBUF_READBACK,
    CMD_GET_SIGNALS,
};

///
/// Gpu command handler type.
///
typedef void (*GpuCommandHandler)( Gpu & r, void * param, size_t size );

///
/// Gpu command handler table.
///
extern const GpuCommandHandler g_gpuCommandHandlers[];

}} // end of file
