Import( 'GN' )

sources = [
    'core.cpp',
    'coreLog.cpp',
	'filesys.cpp'
]

cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )

cluster.addCompileFlags( CPPDEFINES = ['_GN_CORE'] )

GN.newTarget( 'shlib', 'GNcore', [cluster] )
