Import( 'env GN_targets GN_conf' )

env = env.Copy()
env.Append( CPPDEFINES = ['_GN_CORE'] )

core = env.GN_build_shared_library(
    'GNcore',
    env.GN_glob('*.cpp'),
    'pch.h',
    'pch.cpp' )
