Import( 'GN' )

sources = [
    'core.cpp',
    'coreLog.cpp',
]

cluster = GN.newSourceCluster( sources )

cluster.addCompileFlags( CPPDEFINES = ['_GN_CORE'] )

GN.newTarget( 'shlib', 'GNcore', [cluster] )
