Import( 'GN' )

if GN.has_glut and GN.has_fbx :

	sources = [
		'Common.cxx',
		'DrawScene.cxx',
		'GetPosition.cxx',
		'GlFunctions.cxx',
		'InitScene.cxx',
		'main.cxx',
		'SetCamera.cxx',
		'targa.cxx',
	]

	name = 'GNtestFbx'
	GN.NewDefaultTarget( name, GN.BinplaceProgram( GN.BuildProgram( None, name, sources, 'pch.h', 'pch.cpp' ) ) )
