Import( 'GN' )

import sys

# build case list
cases = []
cases += GN.glob( 'base/*.cpp' )
#if 'win32' == env['PLATFORM']: cases += ['gfx/renderer/ogl.cpp']
#if 'win32' == env['PLATFORM']: cases += ['gfx/renderer/d3d.cpp']

# generate cxxtest glue file.
cxxtest = Command(
    'ut.cpp', cases,
    '%s %s --error-printer --include="garnet/GNbase.h" -o $TARGET ${SOURCES.abspath}'%(
        sys.executable,
        File('cxxtestgen.py').srcnode().path)
    )
Depends( cxxtest, 'cxxtestgen.py' )

# build unit test application
cluster = GN.newSourceCluster( [str(cxxtest[0]),'testCommon.cpp'] )
cluster.addCompileFlags( CPPPATH = ['.'] )
if GN.conf['has_boost']: cluster.addCompileFlags( CPPDEFINES = ['HAS_BOOST'] )
GN.newTarget( 'prog', 'GNut', [cluster] )
