Import( 'GN' )

import sys

# build case list
cases = []
cases += GN.glob( 'base/strmap.cpp' )
#cases += GN.glob( 'gfx/*.cpp' )

# generate cxxtest glue file.
cxxtest = Command(
    'ut.cpp', cases,
    '%s %s --error-printer --include="garnet/GNbase.h" -o $TARGET ${SOURCES.abspath}'%(
        sys.executable,
        File('cxxtestgen.py').srcnode().path)
    )
Depends( cxxtest, 'cxxtestgen.py' )

# build unit test application
cluster = GN.newSourceCluster( [str(cxxtest[0]),'testCommon.cpp'] )
GN.newTarget( 'prog', 'GNut', [cluster] )

# disable signed compare with unsigned warning of GCC
if 'gcc' == GN.compiler.name: cluster.addCompileFlags( CCFLAGS=['-Wno-sign-compare'] )
