Import( 'env' )

if 'win32' == env['PLATFORM']:
    env.GN_build_static_library(
        'GNd3d',
        env.GN_glob('*.cpp'),
        'pch.h',
        'pch.cpp' )
    SConscript( 'test/SConscript' )