Import( 'GN' )

import os.path

srcdir = str( Dir('.').srcnode().path )

def doCopy( env, sources ):
    targets = []
    for x in sources:
        src = str(x.srcnode().path)
        dst = os.path.join( GN.distRoot(), 'media', GN.relpath( src, srcdir ) )
        targets.append( env.InstallAs( dst, src ) )
    return targets

sources = GN.glob( "*.*", True )
cluster = GN.newCustomSourceCluster( sources, doCopy )
GN.newNeutralCustomTarget( 'GNmedia', [cluster] )
