Import( 'GN' )
sources = [
	'asciifont.cpp',
	'ase.cpp',
	'bitmapFont.cpp',
	'charBitmap8x13.cpp',
	'fontft2.cpp',
	'line.cpp',
	'misc.cpp',
	'mixedfont.cpp',
	'modelHierarchy.cpp',
	'sprite.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )

if GN.conf['has_fbx']:
	cluster.addCompileFlags(
		CPPPATH = [GN.conf['fbx_inc_path']],
		CPPDEFINES = ['HAS_FBX'] )

Return( 'cluster' )
