Import( 'GN' )
sources = [
    'colorFormat.cpp',
    'createRenderer.cpp',
    'd3d9FormatUtils.cpp',
    'd3d9ShaderUtils.cpp',
    'effect.cpp',
    'fakeRenderer.cpp',
    'image.cpp',
    'imageDDS.cpp',
    'imageJPG.cpp',
    'imagePNG.cpp',
    'imageTGA.cpp',
    'renderState.cpp',
    'shape.cpp',
    'vertex.cpp',
]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
