//
// DO NOT EDIT. Generated by "gencmd.cmd"
//

#include "pch.h"
#include "mtrndrCmd.h"

namespace GN { namespace gfx
{

void func_GET_RENDERER_OPTIONS( Renderer &, void *, size_t );
void func_GET_DISP_DESC( Renderer &, void *, size_t );
void func_GET_D3D_DEVICE( Renderer &, void *, size_t );
void func_GET_OGL_RC( Renderer &, void *, size_t );
void func_GET_CAPS( Renderer &, void *, size_t );
void func_CHECK_TEXTURE_FORMAT_SUPPORT( Renderer &, void *, size_t );
void func_GET_DEFAULT_TEXTURE_FORMAT( Renderer &, void *, size_t );
void func_COMPILE_GPU_PROGRAM( Renderer &, void *, size_t );
void func_CREATE_GPU_PROGRAM( Renderer &, void *, size_t );
void func_CREATE_UNIFORM( Renderer &, void *, size_t );
void func_CREATE_TEXTURE( Renderer &, void *, size_t );
void func_CREATE_VTXBUF( Renderer &, void *, size_t );
void func_CREATE_IDXBUF( Renderer &, void *, size_t );
void func_BIND_CONTEXT( Renderer &, void *, size_t );
void func_REBIND_CONTEXT( Renderer &, void *, size_t );
void func_PRESENT( Renderer &, void *, size_t );
void func_CLEAR_SCREEN( Renderer &, void *, size_t );
void func_DRAW_INDEXED( Renderer &, void *, size_t );
void func_DRAW( Renderer &, void *, size_t );
void func_DRAW_INDEXED_UP( Renderer &, void *, size_t );
void func_DRAW_UP( Renderer &, void *, size_t );
void func_DRAW_LINES( Renderer &, void *, size_t );
void func_PROCESS_RENDER_WINDOW_MESSAGES( Renderer &, void *, size_t );
void func_ENABLE_PARAMETER_CHECK( Renderer &, void *, size_t );
void func_DUMP_NEXT_FRAME( Renderer &, void *, size_t );
void func_GPU_PROGRAM_DESTROY( Renderer &, void *, size_t );
void func_GPU_PROGRAM_INIT( Renderer &, void *, size_t );
void func_UNIFORM_DESTROY( Renderer &, void *, size_t );
void func_UNIFORM_UPDATE( Renderer &, void *, size_t );
void func_TEXTURE_DESTROY( Renderer &, void *, size_t );
void func_TEXTURE_UPDATE_MIPMAP( Renderer &, void *, size_t );
void func_TEXTURE_READ_MIPMAP( Renderer &, void *, size_t );
void func_TEXTURE_BLOB_WRITE( Renderer &, void *, size_t );
void func_TEXTURE_BLOB_READ( Renderer &, void *, size_t );
void func_VTXBUF_DESTROY( Renderer &, void *, size_t );
void func_VTXBUF_UPDATE( Renderer &, void *, size_t );
void func_VTXBUF_READBACK( Renderer &, void *, size_t );
void func_IDXBUF_DESTROY( Renderer &, void *, size_t );
void func_IDXBUF_UPDATE( Renderer &, void *, size_t );
void func_IDXBUF_READBACK( Renderer &, void *, size_t );
void func_GET_SIGNALS( Renderer &, void *, size_t );

const RndrCommandHandler g_rndrCommandHandlers[] = {
&func_GET_RENDERER_OPTIONS,
&func_GET_DISP_DESC,
&func_GET_D3D_DEVICE,
&func_GET_OGL_RC,
&func_GET_CAPS,
&func_CHECK_TEXTURE_FORMAT_SUPPORT,
&func_GET_DEFAULT_TEXTURE_FORMAT,
&func_COMPILE_GPU_PROGRAM,
&func_CREATE_GPU_PROGRAM,
&func_CREATE_UNIFORM,
&func_CREATE_TEXTURE,
&func_CREATE_VTXBUF,
&func_CREATE_IDXBUF,
&func_BIND_CONTEXT,
&func_REBIND_CONTEXT,
&func_PRESENT,
&func_CLEAR_SCREEN,
&func_DRAW_INDEXED,
&func_DRAW,
&func_DRAW_INDEXED_UP,
&func_DRAW_UP,
&func_DRAW_LINES,
&func_PROCESS_RENDER_WINDOW_MESSAGES,
&func_ENABLE_PARAMETER_CHECK,
&func_DUMP_NEXT_FRAME,
&func_GPU_PROGRAM_DESTROY,
&func_GPU_PROGRAM_INIT,
&func_UNIFORM_DESTROY,
&func_UNIFORM_UPDATE,
&func_TEXTURE_DESTROY,
&func_TEXTURE_UPDATE_MIPMAP,
&func_TEXTURE_READ_MIPMAP,
&func_TEXTURE_BLOB_WRITE,
&func_TEXTURE_BLOB_READ,
&func_VTXBUF_DESTROY,
&func_VTXBUF_UPDATE,
&func_VTXBUF_READBACK,
&func_IDXBUF_DESTROY,
&func_IDXBUF_UPDATE,
&func_IDXBUF_READBACK,
&func_GET_SIGNALS,
};

}} // end of file
