Import( 'GN' )

sources = [
	'effectresource.cpp',
	'effectresourcedesc.cpp',
	'gpuresdb.cpp',
	'meshresource.cpp',
	'meshresourcedesc.cpp',
	'modelresource.cpp',
	'simpleWireframeModel.cpp',
	'simpleDiffuseModel.cpp',
	'simpleNormalMapModel.cpp',
    'stdUniform.cpp',
	'textureresource.cpp',
	'uniformresource.cpp',
]

objects = GN.BuildObjects( None, sources, 'pch.h', 'pch.cpp' )
Return( 'objects' )
