Import( 'GN' )

sources = [
	'cmdbuf.cpp',
	'mtidxbuf.cpp',
	'mtgpu.cpp',
	'mtgpuCmd.cpp',
	'mtshader.cpp',
	'mttexture.cpp',
	'mtvtxbuf.cpp',
	'gpuCreator.cpp',
	'gpuDeletor.cpp',
]

objects = GN.BuildObjects( None, sources, 'pch.h', 'pch.cpp' )
Return( 'objects' )
