Import( 'GN' )

sources = [
	'effectresource.cpp',
	'main.cpp',
	'gpuresdb.cpp',
	'modelresource.cpp',
	]

cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
GN.newTarget( 'prog', 'GNtestResourceDB', [cluster] )
