Import( 'GN' )

d3d9_sources = [
	'd3d9App.cpp',
	'd3d9ShaderUtils.cpp',
	'd3d9ThickLine.cpp',
]

d3d11_sources = [
	'dxgiTextureFormat.cpp',
	'd3d11app.cpp',
    'd3d11sprite.cpp',
    'd3d11text.cpp',
   	'd3d11Utils.cpp',
]

sources = []

if GN.has_d3d9:
	sources += d3d9_sources
if GN.has_d3d11:
	sources += d3d11_sources

objects = GN.BuildObjects( None, sources, 'pch.h', 'pch.cpp' )
Return( 'objects' )
