Import( 'GN' )

if GN.has_d3d10 and GN.has_d3dx10:

    import string

    def Fx2Cpp( target, source, env ):
        s = open( source[0].path, 'r' )
        t = open( target[0].path, 'w' )
        for line in s:
            t.write( '"%s \\n"\n'%string.strip( line, '\r\n' ) )
        return None

    fxo = Command(
        'effect.fxo',
        'effect.fx',
        '"%sUtilities\\Bin\\x86\\fxc.exe" /T fx_4_0 /Fo $TARGET $SOURCE'%( GN.GetEnv("DXSDK_DIR") )
        )

    fxh = Command( 'effect.h', 'effect.fx', Fx2Cpp );

    main2 = Command( 'main2.cpp', 'main.cpp', Copy("$TARGET", "$SOURCE") );

    Depends( main2, [fxo,fxh] );

    GN.NewDefaultTarget(
        'GNtestD3D10',
        GN.BinplaceProgram( GN.BuildProgram( None, 'GNtestD3D10', ["main2.cpp"], 'pch.h', 'pch.cpp' ) ) )
