Import( 'GN' )
sources = [
    'oglBasicShaderARB.cpp',
    'oglBasicShaderGLSL.cpp',
    'oglCapsMgr.cpp',
    'oglCharBitmap8x13.cpp',
    'oglContextMgr.cpp',
    'oglDispMgrMsw.cpp',
    'oglDispMgrX11.cpp',
    'oglDrawMgr.cpp',
    'oglFont.cpp',
    'oglIdxBuf.cpp',
    'oglLine.cpp',
    'oglProgramGLSL.cpp',
    'oglQuad.cpp',
    'oglRenderer.cpp',
    'oglResource.cpp',
    'oglResourceMgr.cpp',
    'oglTexture.cpp',
    'oglVtxBufNormal.cpp',
    'oglVtxBufVBO.cpp',
    'oglVtxFmt.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
GN.newTarget( 'shlib', 'GNgfxOGL', [cluster], dependencies = ['GNgfxCommon'] )
