Import( 'GN' )
if GN.has_vulkan:
    name = 'GNtestVulkan'
    GN.NewDefaultTarget( name, GN.BinplaceProgram( GN.BuildProgram( None, name, ['main.cpp'], 'pch.h', 'pch.cpp', extraLibs=['vulkan-1'] ) ) )
