Import( 'GN' )

import sys, os.path

# store Doc generate functor
class DocGenerator:

    def __call__( self, env, sources, bldDir ):

        doxygen = File('#env/bin/mswin/x86/doxygen.exe').path
        genchm = 'YES'

        outdir = Dir(os.path.join( bldDir, 'doc' )).abspath

        chmFileName = os.path.join( outdir, 'reference.chm' )

        doxyFileName = os.path.join( outdir, 'DoxyFile' )

        doxyfile = env.Command(
            doxyFileName, sources,
            '%s $SOURCES OUTPUT_DIRECTORY=%s CHM_FILE=%s GENERATE_HTMLHELP=%s HHC_LOCATION=%s > $TARGET'%(
                sys.executable,
                outdir,
                chmFileName,
                genchm,
                File('#env/bin/mswin/x86/hhc.exe').abspath,
                )
            )

        manual = env.Command(
            chmFileName, doxyFileName,
            '%s $SOURCES'%(doxygen)
            )

        env.Depends( manual, GN.glob( '#src/priv/*.[h|inl]', True ) )
        return manual

Import( 'GN' )
if 'mswin' == GN.compiler.os:
    cluster = GN.newCustomSourceCluster( ['gendoxyfile.py','doxyfile.in'], DocGenerator() )
    GN.newNeutralCustomTarget( 'GNdoc', [cluster] )
