Import( 'GN' )
sources = [
	'arcball.cpp',
	'ase.cpp',
	'bitmapFont.cpp',
	'fontft2.cpp',
	'fpcamera.cpp',
	'simpleDiffuseEffect.cpp',
	]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
