Import( 'GN' )
name = 'GNsampleThickLine'
sources = [
        'main.cpp',
        'orientationBox.cpp',
        'viewfrustum.cpp',
]
GN.NewDefaultTarget( name, GN.BinplaceProgram( GN.BuildProgram( None, name, sources, 'pch.h', 'pch.cpp' ) ) )
