Import( 'env GN_conf' )

import sys, glob

# initialize local environment
env = env.Copy()
env.Append( CPPPATH = ['.'] )
if GN_conf['has_boost']: env.Append( CPPDEFINES = ['HAS_BOOST'] )

# generate cxxtest glue file.
cases   = env.GN_glob('*.cpp', 'base')
cxxtest = env.Command(
    'ut.cpp', cases,
    '%s %s --error-printer --include="garnet/GNbase.h" -o $TARGET ${SOURCES.abspath}'%(
        sys.executable,
        File('cxxtestgen.py').srcnode().path)
    )

# build unit test application
env.GN_build_program( 'GNtest', ['testCommon.cpp',cxxtest] )