Import( 'GN' )

sources = [
	'main.cpp',
]

GN.NewDefaultTarget(
	'GNtoolD3D9DumpViewer',
	GN.BinplaceProgram( GN.BuildProgram( None, 'GNtoolD3D9DumpViewer', sources, 'pch.h', 'pch.cpp' ) ) )
