Import( 'GN' )

import sys, os.path

# build case list
cases = []
cases += GN.Glob( 'base/*.cpp' )
cases += GN.Glob( 'gfx/*.cpp' )

# remove encoding.cpp when compiling with gcc, since gcc can't
# parse GBK strings in the file.
if 'gcc' == GN.cc: cases.remove(os.path.normpath('base/encoding.cpp'))

# generate cxxtest glue file.
cxxtest = Command(
    'ut.cpp', cases,
    '%s %s --error-printer --include="garnet/GNbase.h" -o $TARGET ${SOURCES.abspath}'%(
        sys.executable,
        File('cxxtestgen.py').srcnode().path)
    )
Depends( cxxtest, 'cxxtestgen.py' )

# build unit test application
env = GN.NewBuildEnv()
if 'gcc' == GN.cc: env.Append( CCFLAGS=['-Wno-sign-compare'] )
name = 'GNut'
GN.NewDefaultTarget( name, GN.BinplaceProgram( GN.BuildProgram( env, name, [str(cxxtest[0]),'testCommon.cpp'] ) ) )
