cmake_minimum_required (VERSION 2.8.12)

message("Convert ${INPUT_FILES} to header ${OUTPUT}...")

# Create header for C file
file(WRITE ${OUTPUT} "/* Autogenerated by bin2h */
#pragma once
#include <stdint.h>

")

# Iterate through binary files files
foreach(bin ${INPUT_FILES})
  # Get short filename
  string(REGEX MATCH "([^/]+)$" filename ${bin})
  # Replace filename spaces & extension separator for C compatibility
  string(REGEX REPLACE "\\.| |-" "_" filename ${filename})
  # Convert to lower case
  string(TOLOWER ${filename} filename)
  # Read hex data from file
  file(READ ${bin} filedata HEX)
  # Convert hex data for C compatibility
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," filedata ${filedata})
  # Append data to c file
  file(APPEND ${OUTPUT} "uint8_t ${filename}[] = {${filedata}};\n")
endforeach()