cmake_minimum_required (VERSION 2.8.12)

message("    INPUT_FILES = ${INPUT_FILES}")
message("    OUTPUT = ${OUTPUT}")

# Create header for C file
file(WRITE ${OUTPUT} "/* Autogenerated by str2h */
#pragma once
")

# Iterate through binary files files
foreach(bin ${INPUT_FILES})
  # Get short filename
  string(REGEX MATCH "([^/]+)$" filename ${bin})
  # Replace filename spaces & extension separator for C compatibility
  string(REGEX REPLACE "\\.| |-" "_" filename ${filename})
  # Convert to lower case
  string(TOLOWER ${filename} filename)
  # Read hex data from file
  file(READ ${bin} text)
  # Append data to c file
  file(APPEND ${OUTPUT} "constexpr char ${filename}[] = R\"str2h.cmake(${text})str2h.cmake\";")
endforeach()