Import( 'GN' )
SConscript( dirs=['GPUBenchmark', 'meshConverter','meshViewer'] )
if GN.conf['has_ogl']: SConscript( dirs=['oglInfo'] )
if GN.conf['has_d3d9'] and 'xenon' != GN.compiler.name: SConscript( dirs=['d3d9Wrapper'] )
