Import( 'GN' )

sources = [
	'main.cpp',
	]

cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
#cluster.addCompileFlags( CCFLAGS=['/FAsc'] )
GN.newTarget( 'prog', 'GNtestEngine', [cluster] )
