sources = [
    'basicContextMgr.cpp',
    'basicDispMgr.cpp',
    'basicDrawMgr.cpp',
    'basicRenderer.cpp',
    'basicResourceManager.cpp',
    'renderWindowMsw.cpp',
    'renderWindowX11.cpp',
]
env = Environment()
cluster = env.GN_newSourceCluster( sources, 'pch.h', 'pch.cpp' )
env.GN_newTarget( 'stlib', 'GNgfxCommon', [cluster] )
