Import( 'env' )

objs = []
objs += SConscript( 'app/SConscript' )
objs += SConscript( 'base/SConscript' )
objs += SConscript( 'gfx/SConscript' )
objs += SConscript( 'input/SConscript' )
objs += SConscript( 'win/SConscript' )

env.GN_build_static_library( 'GNbase', objs, pdb = 'GNbase.pdb' )
