sources = []
sources.append( SConscript( 'app/SConscript' ) )
sources.append( SConscript( 'base/SConscript' ) )
sources.append( SConscript( 'gfx/SConscript' ) )
sources.append( SConscript( 'gui/SConscript' ) )
sources.append( SConscript( 'input/SConscript' ) )
#sources.append( SConscript( 'util/SConscript' ) )
sources.append( SConscript( 'win/SConscript' ) )
Environment().GN_newTarget( 'stlib', 'GNbase', sources )
