Import( 'GN' )
sources = [
    'basicInput.cpp',
    'basicInputMsw.cpp',
    'basicInputXInput.cpp',
    'input.cpp',
    'inputDInput.cpp',
    'inputMsw.cpp',
    'inputX11.cpp',
]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
if GN.conf['has_xinput'] : r.addCompileFlags( CPPDEFINES = ['HAS_XINPUT'] )
if GN.conf['has_dinput'] : r.addCompileFlags( CPPDEFINES = ['HAS_DINPUT'] )
Return( 'r' )
