Import( 'GN' )
sources = [
    'basicInput.cpp',
    'basicInputMsw.cpp',
    'basicInputXInput.cpp',
    'input.cpp',
    'inputDInput.cpp',
    'inputMsw.cpp',
    'inputX11.cpp',
]
r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
Return( 'r' )
