Import( 'GN' )
sources = [
    'xenonCapsMgr.cpp',
    'xenonContextMgr.cpp',
    'xenonDispMgr.cpp',
    'xenonDrawMgr.cpp',
    'xenonGpuProgramASM.cpp',
    'xenonGpuProgramHLSL.cpp',
    'xenonIdxBuf.cpp',
    'xenonLine.cpp',
    'xenonRenderer.cpp',
    'xenonRenderTargetMgr.cpp',
    'xenonResource.cpp',
    'xenonResourceManager.cpp',
    #'xenonSampler.cpp',
    'xenonTexture.cpp',
    'xenonVertexDecl.cpp',
    'xenonVtxBuf.cpp',
]
cluster = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
target  = GN.newTarget( 'shlib', 'GNrndrXenon', [cluster], dependencies = ['GNrndrCommon'] )
