sources = [
    'core.cpp',
    'coreEffectDict.cpp',
    'coreSearchResource.cpp',
    'coreShaderDict.cpp',
    'coreTextureDict.cpp',
]

env = Environment()

cluster = env.GN_newSourceCluster( sources )

cluster.addCompileFlags( CPPDEFINES = ['_GN_CORE'] )

env.GN_newTarget( 'shlib', 'GNcore', [cluster] )
