Import( 'GN' )

sources = [
    'core.cpp',
    'coreEffectDict.cpp',
    'coreRawResourceDict.cpp',
    'coreSearchResource.cpp',
    'coreShaderDict.cpp',
    'coreTextureDict.cpp',
]

cluster = GN.newSourceCluster( sources )

cluster.addCompileFlags( CPPDEFINES = ['_GN_CORE'] )

GN.newTarget( 'shlib', 'GNcore', [cluster] )
