Import( 'GN' )
sources = [
	SConscript( 'base/SConscript' ),
	SConscript( 'd3d/SConscript' ),
	SConscript( 'gpu/SConscript' ),
	SConscript( 'gpures/SConscript' ),
	SConscript( 'misc/SConscript' )
	]

t = GN.newTarget( 'stlib', 'GNgfxUtil', sources )

if GN.conf['has_fbx']:
	t.addLinkFlags( LIBPATH = [GN.conf['fbx_lib_path']] )
	t.externalDependencies = GN.conf['fbx_libs']

