Import( 'GN' )
sources = [
    'basicGpu.cpp',
    'basicGpuMsw.cpp',
    'basicGpuX11.cpp',
    'basicSurface.cpp',
]
env = GN.NewBuildEnv()
objects = GN.BuildObjects( env, sources, 'pch.h', 'pch.cpp' )
Return( 'objects' )
