Import( 'GN' )

sources = [
	'boundingVolume.cpp',
	'clock.cpp',
	'codepage.cpp',
	'codepageICONV.cpp',
	'codepageMSWIN.cpp',
	'codepageXenon.cpp',
	'core.cpp',
	'coreLog.cpp',
	'filesys.cpp',
	'debug.cpp',
	'dict.cpp',
	'endian.cpp',
	'file.cpp',
	'hashmap.cpp',
	'log.cpp',
	'memory.cpp',
	'misc.cpp',
	'path.cpp',
	'profiler.cpp',
	'registry.cpp',
	'sharedLib.cpp',
	'spinloop.cpp',
	'string.cpp',
	'syncmsw.cpp',
	'syncposix.cpp',
	'threadmsw.cpp',
	'threadposix.cpp',
	'variant.cpp',
	'xml.cpp',
]

r = GN.newSourceCluster( sources, 'pch.h', 'pch.cpp' )
if GN.conf['has_iconv'] :
    r.addCompileFlags( CPPDEFINES = ['HAS_ICONV=1'] )
    r.externalDependencies += [GN.conf['iconv_lib']]
Return( 'r' )
